### ISSUE TITLE
建议主题版本显示

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#10]
大佬，晚上好！
建议在主题的这里加上版本号，这样更新后能直接看到当前主题的最新版本。

![image](https://user-images.githubusercontent.com/19606627/141683540-46264da3-6b84-40a2-9c95-732eeda43565.png)

**Comment by qinhua** [comment]
@bxbdba 这个估计要向 `halo-admin` 这个项目提 `issue`，目前这些信息其实都有，只是没有展示出来。

我之前也想把版本加上去，但没时间去贡献😆。

**Comment by bxbdba** [comment]
好的！谢谢大佬！

**Comment by ruibaby** [comment]
> @bxbdba 这个估计要向 `halo-admin` 这个项目提 `issue`，目前这些信息其实都有，只是没有展示出来。
> 
> 我之前也想把版本加上去，但没时间去贡献laughing。

已经在计划之内，关于主题的设置可能会在 1.5 的时候重写。

**Comment by bxbdba** [comment]
好，谢谢两位大佬！

**Comment by qinhua** [comment]
@bxbdba 目前已在前台做了版本展示，可在控制台查看当前主题的版本信息。
这个功能等后台管理系统支持就好了，先关了。
