### ISSUE TITLE
Halo 1.5 已发布，可以考虑适配一下。

### ISSUE THREAD

**Issue by ruibaby** [qinhua/halo-theme-joe2.0#101]
### 你当前使用的版本

1.0.9

### 你的建议是否涉及到一些现有的问题？

数学公式和图表的问题。

### 描述你想实现的效果

目前 Halo 1.5 已经内置支持数学公式和 mermaid 图标的渲染。可以考虑移除 mermaid 的依赖（如果有），数学公式只需要引入：

```
<link rel="stylesheet" href="https://unpkg.com/katex@0.12.0/dist/katex.min.css" />
```

在主题设置中可以设置一个选项，是否开启 Katex 样式渲染即可。

PS：可以将 require 改为 1.5.0。

感谢你为 Halo 做出的贡献。

**Comment by qinhua** [comment]
@ruibaby 好嘞，最近会抽时间适配一下新版。

**Comment by qinhua** [comment]
@ruibaby 已处理
