### ISSUE TITLE
温馨提示无法关闭

### ISSUE THREAD

**Issue by hapke24** [qinhua/halo-theme-joe2.0#102]
### 是什么版本出现了此问题？

2.0

### Halo 版本

1.4.17

### 平台

桌面端

### 操作系统

Windows11

### 浏览器

Edge

### 描述缺陷

温馨提示无法关闭
- 这是设置
![image](https://user-images.githubusercontent.com/49407099/159637390-ca37e1b0-b261-4af9-b8b4-ec04bcd6b235.png)
- 这是显示
![image](https://user-images.githubusercontent.com/49407099/159637467-2cc9d5fe-1668-429c-b352-b163bf3dd663.png)
使用本地127.0.0.1测试和和部署后带域名测试都不行
- 确定了非缓存问题
![image](https://user-images.githubusercontent.com/49407099/159637715-5ab71ff3-509c-4a94-a7c7-e69479b9f116.png)
- 温馨提示文案更改没有问题
![image](https://user-images.githubusercontent.com/49407099/159638228-406c4b06-cf02-4dc4-8c7d-f217e125b279.png)

![image](https://user-images.githubusercontent.com/49407099/159638186-b41cc90d-4ab3-451a-9b84-4cfe93ce479a.png)

### 如何复现

在后台关闭温馨提示后打开文章查看即可复现

### 期望结果

温馨提示按钮能够关闭温馨提示

**Comment by qinhua** [comment]
@hapke24 之前改错了一个判断，后续版本会恢复，可手动修改一下：
在主题编辑中修改 `post.ftl` 第 53 行为以下内容：
```html
<#if settings.enable_passage_tips && enable_passage_tips == 'true'>
```

**Comment by livejq** [comment]
嗯，可以了

**Comment by qinhua** [comment]
`V1.0.10` 已修复，请升级已解决，感谢支持🙏
