### ISSUE TITLE
文章目录无法定位到相遇的文章正文位置

### ISSUE THREAD

**Issue by moyueheng** [qinhua/halo-theme-joe2.0#103]
### 是什么版本出现了此问题？

2.0

### Halo 版本

1.5

### 平台

桌面端

### 操作系统

Mint OS

### 浏览器

Chrome

### 在线站点地址

http://coderxiaomo.top/archives/zhe-shi-di-yi-pian-halo-wen-zhang

### 描述缺陷

![image](https://user-images.githubusercontent.com/54298540/159884739-3969fe19-2bb5-4bdd-a619-c76f9c32c728.png)
文章目录无法定位到相遇的文章正文位置

### 如何复现

打开在线站点地址便可看到情况

**Comment by qinhua** [comment]
@moyueheng 我这边看这个文章未能复现

**Comment by moyueheng** [comment]
> @moyueheng 我这边看这个文章未能复现

知道了是halo1.5的原因，感谢作者

**Comment by moyueheng** [comment]
> @moyueheng 我这边看这个文章未能复现

因为我以及回退到halo1.5了

**Comment by shy-share** [comment]
@moyueheng 你的博客挂掉了
![image](https://user-images.githubusercontent.com/50973219/165654249-2f99b4e4-2dca-41ae-b2ce-be68252daff4.png)

**Comment by qinhua** [comment]
@moyueheng `V1.0.10` 已支持，请升级已解决，感谢支持🙏

**Comment by qinhua** [comment]
@moyueheng `V1.0.10` 已支持，请升级已解决，感谢支持🙏
