### ISSUE TITLE
希望能够将文章页获取主题配置的代码独立出一个js文件

### ISSUE THREAD

**Issue by hapke24** [qinhua/halo-theme-joe2.0#105]
### 你当前使用的版本

1.0.7

### 你的建议是否涉及到一些现有的问题？

获取主题配置的代码有2000多行，每打开一个页面都加载一遍感觉对带宽和搜索引擎爬取都不够友好
![image](https://user-images.githubusercontent.com/49407099/160997138-f2720225-e628-4f3d-835b-484a64c5d3bf.png)
![image](https://user-images.githubusercontent.com/49407099/160996754-3dd2f77c-60b6-42d6-9e68-0c603c26b199.png)
![image](https://user-images.githubusercontent.com/49407099/160996836-4d033fad-4202-4989-b193-5112e8d36bbb.png)

### 描述你想实现的效果

希望能够精简代码或者打包成一个独立的js文件

**Comment by qinhua** [comment]
@hapke24 由于是后端渲染，这个配置目前只能放在 ftl 模板中才能获取到，js文件中无法直接取到 freemarker 中的数据。
当然，也可以通过ajax接口获取，但是那样就有一定滞后了。
另外，SEO 爬取阶段，数据都已经渲染出来了，其实没什么影响。

> 关于项目结构，后续会做优化的。

**Comment by qinhua** [comment]
@hapke24 新版本已对相关代码做了优化
