### ISSUE TITLE
最新主题报错

### ISSUE THREAD

**Issue by 643063150** [qinhua/halo-theme-joe2.0#106]
### 是什么版本出现了此问题？

V 1.0.9

### Halo 版本

2.0

### 平台

桌面端

### 操作系统

win2019server

### 浏览器

chrome

### 在线站点地址

http://blog.zppnet.cn/

### 描述缺陷

最新版本网站报错

**Comment by qinhua** [comment]
@643063150
分析：通过查看请求的资源 URL，发现还是使用的 V1.0.8 的主题。
原因：由于 V1.0.8 的主题默认还是使用的 jsdelivr 的 CDN 去加载静态资源，但是目前这个 CDN 已经做了访问限制，所以很多地方已经用不了了。
解决方案：可以选择去 `主题设置-其它` 中关闭  `从CDN加载资源`  或者升级到 V1.0.9 的主题。

Peace, 感谢您对本主题的支持！

**Comment by 643063150** [comment]
> @643063150 由于 分析：通过查看请求的资源 URL，发现还是使用 V1.0.8 的主题。 ：V1.0.8 的主题默认还是使用 jsdelivr 的 CDN 去加载资源的原因，但是目前这个 CDN 做了访问限制，所以很多地方已经用不了了。 解决方案：可以选择去`主题设置-其它`中关闭 `从CDN加载资源` 或者升级到V1.0.9的主题。
> 
> 和平，感谢您对本主题的支持！

因为1.0.9不能用我回退到1.0.8了 用上1.0.9后网站直接只有文字报错了,现在我重新升级到1.0.9  可以看下 错误已经复现

**Comment by qinhua** [comment]
@643063150 因为 V1.0.9 有一些新增的配置，所以需要你进入主题设置，执行一次保存操作后再试试。

**Comment by 643063150** [comment]
开启全局绝对路径后错误消失

**Comment by qinhua** [comment]
> 开启全局绝对路径后错误消失

ok，这里我检查一下
