### ISSUE TITLE
异步加载

### ISSUE THREAD

**Issue by 1357885013** [qinhua/halo-theme-joe2.0#107]
### 你当前使用的版本

1.0.9

### 你的建议是否涉及到一些现有的问题？

打开文章时的响应时间异常高。

### 描述你想实现的效果

页面快速响应

### 描述一些方案

请求文章时用到了freemark自定义命令来显示 文章总数、评论总数这些数据拖慢了速度， 可否在文章正文加载完成并显示后再异步加载其它信息

### 附加信息

<img width="1180" alt="屏幕截图 2022-03-31 203701" src="https://user-images.githubusercontent.com/25767027/161205724-7f4f0d72-effd-4403-83bf-127fcb9786e4.png">

**Comment by qinhua** [comment]
@1357885013
这个还真没注意到，能告知一下这个耗时怎么查看的吗，或者有什么实际建议的方案呢

**Comment by 1357885013** [comment]
这个耗时是用xrebel查看的 ， 建议分两步或多步加载， 第一步加载正文，然后用ajax加载其它的统计信息

**Comment by 1357885013** [comment]
<@postTag method="listByCategoryId" categoryId="${id}"> 就是这种自定义标签，虽然就写了一句，但是是要查询数据库的，这个最慢了， 我的服务器查这个就要1s， 而且 你这一句重复写几次就查几次数据库

**Comment by Qxin-X** [comment]
> ```
> <@postTag method="listByCategoryId" categoryId="${id}"> 就是这种自定义标签，虽然就写了一句，但是是要查询数据库的，这个最慢了， 我的服务器查这个就要1s， 而且 你这一句重复写几次就查几次数据库
> ```

期待异步加载

**Comment by 1357885013** [comment]
不需要了， 发现是相关文章最占用时间， 把相关文章注释掉后，速度由6秒变成1秒不到

**Comment by Qxin-X** [comment]
> 不需要了， 发现是相关文章最占用时间， 把相关文章注释掉后，速度由6秒变成1秒不到

注释掉文章？是删掉吗？

**Comment by 1357885013** [comment]
> 

相关文章的显示在设置里可以关掉， 如果文章所在分类里文章非常多的话查询相关文章会花费大量时间，否则就不需要关
