### ISSUE TITLE
目录问题

### ISSUE THREAD

**Issue by loongzcode** [qinhua/halo-theme-joe2.0#109]
### 是什么版本出现了此问题？

2.0

### Halo 版本

1.5.1

### 平台

桌面端

### 操作系统

win10

### 浏览器

谷歌浏览器

### 在线站点地址

lyj

### 描述缺陷

页面滚动到最下面，目录最后一条不会变成选中状态

### 附加信息

![image](https://user-images.githubusercontent.com/55130487/161903366-a7feed9e-bb72-4156-8114-cdb6d808dda1.png)

**Comment by qinhua** [comment]
@loongzcode 
哈哈，这种应该属于正常现象，是滚动目录的默认行为，也没有计划去处理，当然你也可以自行优化。
因为底部没有多余空间，滚不动了，无法到达那个指定位置，自然不会去做选中状态。
为了选中效果去动态追加高度得不偿失，这里打开评论就刚好可以补上。

**Comment by qinhua** [comment]
不计划处理
