### ISSUE TITLE
代码块复制问题

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#11]
大佬，你好！
我这边在使用你的主题的时候，在使用中发现复制代码块时，复制过来的是一行，建议复制也能将代码块的格式复制过来。
举例：
代码块有4行代码，我复制4行到VS CODE编辑器后，发现是一整行。
![image](https://user-images.githubusercontent.com/19606627/141730071-330001aa-b050-4561-929f-c5ac669c1f07.png)

**Comment by qinhua** [comment]
@bxbdba 😔 这个我也发现了，今天早上已经处理了，换成 `pre` 标签了，理论上 `xmp` 也可以。 
好像只是手动复制有影响，点击复制按钮是正常的。

**Comment by bxbdba** [comment]
是的，测试点击复制按钮可以，选中手动复制的是下个小版本修复吗？

**Comment by qinhua** [comment]
是的 🙆

**Comment by qinhua** [comment]
已修复
