### ISSUE TITLE
文章评论问题

### ISSUE THREAD

**Issue by loongzcode** [qinhua/halo-theme-joe2.0#110]
### 是什么版本出现了此问题？

2.0

### Halo 版本

1.5.1

### 平台

桌面端

### 操作系统

win10

### 浏览器

谷歌浏览器

### 在线站点地址

lyjnotes.info

### 描述缺陷

为什么我开启了评论，还说博主关闭了所有页面的评论

**Comment by qinhua** [comment]
@loongzcode 请检查是否开启了绿色模式，此模式为备案模式，自动屏蔽所有特效、广告和评论
