### ISSUE TITLE
建议"配置本站点由xxx云提供云服务" 改为自定义填写内容

### ISSUE THREAD

**Issue by RalstonLiu** [qinhua/halo-theme-joe2.0#111]
### 你当前使用的版本

1.0.9

### 你的建议是否涉及到一些现有的问题？

建议把"配置本站点由xxx云提供云服务" 里面的“xxx云”改为可以自定义填写的内容，默认的几个云厂家太少了，哈哈

### 描述你想实现的效果

可以自己填入自己所使用的主机商，并且文字部分可以点击超链接跳转

**Comment by qinhua** [comment]
@RalstonLiu 可以，和博主栏的社交图标一样处理

**Comment by qinhua** [comment]
@RalstonLiu 已支持
