### ISSUE TITLE
API has been disabled by blogger currently

### ISSUE THREAD

**Issue by jeremy526** [qinhua/halo-theme-joe2.0#113]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.5.2

### 平台

桌面端

### 操作系统

win 10

### 浏览器

chrome 100.0.4896.127

### 在线站点地址

http://124.70.5.37/

### 描述缺陷

![image](https://user-images.githubusercontent.com/59838072/163509317-fa08ff88-d67f-41ff-9faf-5da08377aca1.png)
**管理后台找不到可以配置AccessKey的地方 （不知道是不是1.5.2版本太新的缘故**

### 如何复现

首页刷新即可

**Comment by keleen** [comment]
我遇到了同样的问题，不过我翻看作者的 blog 的时候找到了答案
[主题安装与使用](https://bbchin.com/archives/halo-theme-joe20)

如何设置具体操作步骤如下
1. 登录后在系统->博客设置->右上角点击【切换到高级选项】
![image](https://user-images.githubusercontent.com/9244723/163538099-debf7dab-8682-4cc2-ab6d-e12eeb62a994.png)
2. 在高级选项里面选择 【API设置】tab页签，在标签下面填写 Access Key，然后保存
![image](https://user-images.githubusercontent.com/9244723/163538154-6de8ccc9-134d-4d91-88f1-38c2400b8e89.png)
3. 在外观->主题设置->基础设置中设置 Access Token，与第二步的值一致即可，然后保存
![image](https://user-images.githubusercontent.com/9244723/163538456-ed476965-d3d3-4f42-83c4-d09bf2e83110.png)
4. 这样设置完毕后就不会在报错了。

**Comment by jeremy526** [comment]
感谢！！
