### ISSUE TITLE
API has been disabled by blogger currently

### ISSUE THREAD

**Issue by HJHY** [qinhua/halo-theme-joe2.0#114]
### 是什么版本出现了此问题？

v1.0.9

### Halo 版本

1.5.2

### 平台

桌面端

### 操作系统

window 11

### 浏览器

chrome

### 描述缺陷

刷新前端网页出现 API has been disabled by blogger currently
同时后台出现2022-04-23 23:22:54.633 ERROR 14612 --- [tp1687627235-47] .s.h.DefaultAuthenticationFailureHandler : Authentication failure: [API has been disabled by blogger currently], status: [403 FORBIDDEN], data: [null] 问题

**Comment by qinhua** [comment]
@mxlt02 请先读文档 [Joe2.0 主题安装&更新](https://bbchin.com/archives/halo-theme-joe20#-%E5%BF%85%E8%AF%BB)

**Comment by mxlt02** [comment]
@我有什么事吗?

**Comment by qinhua** [comment]
> @我有什么事吗?
哈哈，搞错了
