### ISSUE TITLE
主题搜索功能提升建议，可否不区分大小写，做模糊搜索？

### ISSUE THREAD

**Issue by RalstonLiu** [qinhua/halo-theme-joe2.0#116]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.5.2

### 平台

桌面端

### 在线站点地址

https://blog.laoda.de/

### 描述缺陷

输入`nextcloud`出现的结果如下：
![image-20220429120023837](https://img.laoda.de/i/2022/04/29/julu1l_7.webp)

输入`Nextcloud`出现的结果如下：

![image-20220429120056450](https://img.laoda.de/i/2022/04/29/jusub0_7.webp)

现在需要输入精确的字符（比如大小写）才能搜索出对应的内容，似乎无法做到模糊搜索。

### 期望结果

输入nextcloud或者是Nextcloud，甚至是next或者是cloud，都能出现和Nextcloud相关的内容。

类似这个：

![image-20220429120056450](https://img.laoda.de/i/2022/04/29/jusub0_7.webp)

**Comment by JohnNiang** [comment]
See <https://github.com/halo-dev/halo/issues/2637> for more.
