### ISSUE TITLE
数学公式显示错误

### ISSUE THREAD

**Issue by ml12580gmail** [qinhua/halo-theme-joe2.0#117]
是什么版本出现了此问题？
1.0.9

Halo 版本
1.5.0

平台
桌面端

操作系统
win10

浏览器
Google Chrome

在线站点地址
https://lxtx.work/archives/%E5%86%8D%E8%81%8A%E8%81%8A%E6%96%90%E6%B3%A2%E9%82%A3%E5%A5%91%E6%95%B0%E5%88%97

描述缺陷
在页面无法正确显示markdown的数学公式，有2处

markdown语言1：
$$
\frac{1}{\sqrt{5}}[(\frac{(1+\sqrt{5})}{2})^n-(\frac{(1-\sqrt{5})}{2})^n]
$$

错误显示1：
![b4356e530138eafe0a05589a9f23e82](https://user-images.githubusercontent.com/52950416/166106977-f08b0bbf-91ce-4333-9653-6627756d118e.png)

后台正确显示1：

![48ada413877495d23cd21a74551f51b](https://user-images.githubusercontent.com/52950416/166107035-308e68cc-4c70-4980-9f0d-167bc156d7ef.png)

markdown语言2：
$$
a^{11}=a^{(1+2+8)}=[1*(a^1)]*[1*(a^2)]*[0*a^4]*[1*(a^8)]
$$

错误显示2：
![image](https://user-images.githubusercontent.com/52950416/166107090-865d6b00-176f-4f96-89c6-3b9c398ab69a.png)

后台正确显示2：
![e21db0c4334080107df91f9fb306d21](https://user-images.githubusercontent.com/52950416/166107117-03201744-bf70-474b-aefa-c773e0b10066.png)

**Comment by qinhua** [comment]
@ml12580gmail 是否在主题设置-文章页中开启了 ‘’数学公式支持“ 呢？

**Comment by qinhua** [comment]
@ml12580gmail 建议升级主题到最新版本已支持 `Halo 1.5.x`

**Comment by ml12580gmail** [comment]
@qinhua 多谢，开启后解决了
