### ISSUE TITLE
LOGO配置问题

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#12]
我这边看到导航条那里有个配置，是否展示博客LOGO，但是没有看到设置LOGO图片的地方。
![image](https://user-images.githubusercontent.com/19606627/141742947-e9ef6dbb-904b-48f0-b32f-f23e6361bb7e.png)

**Comment by qinhua** [comment]
@bxbdba 这个我觉得没必要啊，后台管理中就可以设置了，不想做太多重复的东西。除非想这个主题单独有个头像 😆

**Comment by bxbdba** [comment]
额额，看到了，我的问题。。
