### ISSUE TITLE
看板娘

### ISSUE THREAD

**Issue by Qxin-X** [qinhua/halo-theme-joe2.0#120]
### 是什么版本出现了此问题？

V1.0.10

### Halo 版本

1.5.2

### 平台

桌面端

### 操作系统

win10

### 浏览器

edge

### 描述缺陷

看板娘板块用不了了。

### 如何复现

后台主题设置打开看板娘，无法使用，控制台报 403 

### 期望结果

是否移除该板块，或者有搭建服务的计划？

### 附加信息

![1651502696(1)](https://user-images.githubusercontent.com/66522154/166254965-64485326-7632-487a-aaf6-6d68e209ba2a.jpg)

**Comment by faonecze** [comment]
第一个报错,你也有啊.那是做什么的?也是`看板娘`的?

**Comment by Qxin-X** [comment]
> 第一个报错,你也有啊.那是做什么的?也是`看板娘`的?

第一个报错是访问统计的，正常了

**Comment by qinhua** [comment]
@Qxin-X 还是 jsdelivr 的问题

**Comment by Qxin-X** [comment]
> @Qxin-X 还是 jsdelivr 的问题

好的
