### ISSUE TITLE
启用`展示访问量数据`但不是每次都能加载出来

### ISSUE THREAD

**Issue by faonecze** [qinhua/halo-theme-joe2.0#122]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.5.2

### 平台

桌面端

### 操作系统

Manjaro

### 浏览器

chrome

### 在线站点地址

auok.run

### 描述缺陷

![](https://img.cnelite.org/img-url/2205/54d1e88237043d01.png)

启用`展示访问量数据`,很多时候显示都是没有数据的...这是为啥?

### 如何复现

无

### 期望结果

无

### 附加信息

无

**Comment by Qxin-X** [comment]
我猜应该跟缓存有关，我用的是 redis 缓存

**Comment by qinhua** [comment]
@Qxin-X 卜算子的服务问题

**Comment by Qxin-X** [comment]
> @Qxin-X 卜算子的服务问题

好的，那这个就没办法了
