### ISSUE TITLE
友情链接页面切换“分组”显示之后，只能显示一小部分友链

### ISSUE THREAD

**Issue by RalstonLiu** [qinhua/halo-theme-joe2.0#123]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.5.2

### 平台

桌面端

### 在线站点地址

https://blog.laoda.de/links

### 描述缺陷

网站的友情链接比较多（50+），友情链接的展示方式有“分组“和“列表”两种，

![](https://img.laoda.de/i/2022/05/04/10p88cf.webp)

当切换为“列表”的时候，所有友情链接都能显示出来；
![](https://img.laoda.de/i/2022/05/04/10o9h0g.webp)

当切换为“分组”显示之后，只能显示一小部分友链，而且没有下一页的提示，导致没显示出友链的小伙伴以为自己的友情链接被下了……

![](https://img.laoda.de/i/2022/05/04/10nf7zw.webp)

### 期望结果

是否考虑当切换为“分组”显示之后，可以显示全部的友链（可以一页显示，也可以分页显示）

**Comment by qinhua** [comment]
@RalstonLiu 这个不能算是 `bug`。前台分组只会展示分组下的数据，如果数据不属于任何分组，自然就查不出来，也不会展示。
您可以到 `后台管理-页面-所有页面-友情链接` 中检查一下，看那些不展示的链接是否都没有指定分组。
感谢支持🙏

**Comment by RalstonLiu** [comment]
> @RalstonLiu 这个不能算是 `bug`。前台分组只会展示分组下的数据，如果数据不属于任何分组，自然就查不出来，也不会展示。 您可以到 `后台管理-页面-所有页面-友情链接` 中检查一下，看那些不展示的链接是否都没有指定分组。 感谢支持🙏

是的，是我这边没有指定分组😅

感谢作者开发如此优秀的主题！
