### ISSUE TITLE
建议设置增加搜索

### ISSUE THREAD

**Issue by Cyiming** [qinhua/halo-theme-joe2.0#127]
### 你当前使用的版本

1.0.10

### 你的建议是否涉及到一些现有的问题？

设置功能越来越多 查找很不便利 建议设置页面增加搜索

### 描述你想实现的效果

搜索到内容 直接定位到设置选项

**Comment by qinhua** [comment]
@Cyiming 提错项目啦，这个需求需要 `halo-admin` 这个项目来支持。

**Comment by Cyiming** [comment]
> @Cyiming 提错项目啦，这个需求需要 `halo-admin` 这个项目来支持。

哦哦 我不太懂 是需要halo官方支持么 在那里提

**Comment by qinhua** [comment]
> > @Cyiming 提错项目啦，这个需求需要 `halo-admin` 这个项目来支持。
> 
> 哦哦 我不太懂 是需要halo官方支持么 在那里提

https://github.com/halo-dev/halo-admin
