### ISSUE TITLE
评论无法添加空格

### ISSUE THREAD

**Issue by JOCK-ONE** [qinhua/halo-theme-joe2.0#13]
**描述缺陷**

在评论里按空格，不会输入空格，而是向下滚动

**如何复现**

复现步骤如下:

1. 打开一篇文章
2. 点击评论框
3. 按空格
4. 发生错误

**期望结果**
输入一个空格

**实际结果结果**
页面向下滚动，无法输入空格

**Comment by qinhua** [comment]
@JOCK-ONE 发现了，可能是改其它地方时影响了这边，我修一下哈，下版本见，感谢 😝

**Comment by qinhua** [comment]
@JOCK-ONE 已修复
