### ISSUE TITLE
评论查看内容失效

### ISSUE THREAD

**Issue by little-2pig** [qinhua/halo-theme-joe2.0#130]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.4.17

### 平台

桌面端

### 操作系统

win10

### 浏览器

chrome

### 在线站点地址

www.little2pig.work

### 描述缺陷

评论得以查看内容功能失效，<joe-hide></joe-hide>组件失效，上一版本1.0.9还正常

**Comment by qinhua** [comment]
新版本去除了之前那个有问题的组件 `joe-hide`，现在只需要用元数据 `enable_read_limit` 控制即可实现。请参见文档 [如何设置文章仅评论后可见？](https://bbchin.com/archives/halo-theme-joe20#18%E3%80%81%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E6%96%87%E7%AB%A0%E4%BB%85%E8%AF%84%E8%AE%BA%E5%90%8E%E5%8F%AF%E8%A7%81%EF%BC%9F)
