### ISSUE TITLE
png封面在轮播图使用淡入效果出现重叠

### ISSUE THREAD

**Issue by deadmau5v** [qinhua/halo-theme-joe2.0#132]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.5.3

### 平台

桌面端

### 操作系统

Windows 10

### 浏览器

Edge

### 在线站点地址

https://note.deadmau5v.cool/

### 描述缺陷

png文章封面 在轮播图使用淡入效果出现重叠

### 如何复现

文章封面使用png格式 动画效果使用淡入

### 期望结果

期待不要再叠了

### 附加信息

![image](https://user-images.githubusercontent.com/88039301/169890409-257b68a0-596a-464d-9736-6ec2bad0172d.png)

**Comment by qinhua** [comment]
@deadmau5v 我看您使用的图片是带通道的透明 png 图片，这样在使用淡入淡出动画的时候，实际上是透明度变化，肯定无法避免会出现重叠的。可以选用其他动画方式，有些东西不可能两全齐美的。
就保持您目前这种切换方式即可，很棒的。
