### ISSUE TITLE
无法本地安装和无法修改配置

### ISSUE THREAD

**Issue by PawNzZi** [qinhua/halo-theme-joe2.0#133]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.5.3

### 平台

桌面端

### 操作系统

win10

### 浏览器

chrome

### 描述缺陷

halo版本为1.5.3，使用本地安装时提示“该主题仅支持1.5.0以上版本”的错误提示，导致无法安装。但是我通过把文件上传到服务器的主题目录下，刷新halo后显示已经安装了该主题，但是在修改配置时无法保存，http的statuscode为500

**Comment by qinhua** [comment]
这是一个遗留问题，需要先手动把主题配置清空，再重装
