### ISSUE TITLE
绿色模式下出现诡异问题

### ISSUE THREAD

**Issue by devzwy** [qinhua/halo-theme-joe2.0#137]
### 是什么版本出现了此问题？

前端代码时最新的

### Halo 版本

latest 1.5.3

### 平台

桌面端

### 操作系统

Windows10

### 浏览器

360

### 在线站点地址

https://www.wdsf.top

### 描述缺陷

绿色模式下出现了点赞按钮；底部有按钮没法点击；麻烦看下视频；

### 期望结果

绿色模式应该影藏底部诡异没法点击的按钮；
不应该出现点赞按钮

### 附加信息

[诡异bug](https://download.wdsf.top/halo/sqbug.mp4)

**Comment by qinhua** [comment]
@devzwy 我看页面现在好像没这个问题拉

**Comment by devzwy** [comment]
那是因为我现在关闭了绿色模式~

有时间辛苦修复下。

谢谢啦
