### ISSUE TITLE
评论MarkDown渲染问题

### ISSUE THREAD

**Issue by JOCK-ONE** [qinhua/halo-theme-joe2.0#14]
在评论里使用md 渲染有问题，间隔太大

**额外信息**
![image](https://user-images.githubusercontent.com/63354237/141943744-3b479b3d-aef2-48db-9963-2a764b28e051.png)

**Comment by qinhua** [comment]
@JOCK-ONE 我还没在里面输入过  `MarkDown`，所以不知道有这个问题，如果只是样式不美观，那就是小意思，不过我要先处理紧急的问题，这个可能会延后处理，这几天比较忙。

**Comment by qinhua** [comment]
@JOCK-ONE 已在原基础上做了一些样式优化，不太彻底，但也够用了。
