### ISSUE TITLE
文章搜索时，英文区分大小写

### ISSUE THREAD

**Issue by WinJayX** [qinhua/halo-theme-joe2.0#142]
### 你当前使用的版本

Joe2.0

### 你的建议是否涉及到一些现有的问题？

在首页进行文章搜索时，输入英文关键字：“MySQL”、“mysql”、“MySql”、“MySql" 等搜索出来的文章都不一样。

### 描述你想实现的效果

我想实现不管输入什么关键字，都不区分大小写来进行搜索。

**Comment by qinhua** [comment]
@WinJayX 主题不处理这个问题，halo 官方已有相关 issue，请关注 [](https://github.com/halo-dev/halo/issues/1545)
