### ISSUE TITLE
打开网站错位

### ISSUE THREAD

**Issue by xianweibo** [qinhua/halo-theme-joe2.0#143]
### 是什么版本出现了此问题？

joe2.0

### Halo 版本

halo1.5.3

### 平台

桌面端

### 在线站点地址

https://www.zhuhongshengshi.com/

### 描述缺陷

我得网站变成下面这样的错位，手机访问就没问题。
cookies，还有缓存都清理过了，还是一样，请问怎么搞？
![图片](https://user-images.githubusercontent.com/34569466/179393691-f25ce40e-0c33-42a9-9aad-81e918853aa8.png)

**Comment by xianweibo** [comment]
用edge， firefox， chrome都是这样
cookies和缓存都清理了。还是一样。

**Comment by qinhua** [comment]
@xianweibo 通过查看您的网站，发现你的css资源域名是 http 协议的。这样的话，当您通过 https 的域名去访问站点的时候，大部分浏览器会阻止加载 http 来源的资源，所以造成您的 css 加载不出来。
因此，只需要修改静态资源的访问路径为 https 开头即可。

**Comment by qinhua** [comment]
> > 
> 
> 请问这个怎么做到？ 我用得是宝塔得nginx
> 
> ![1658410006751](https://user-images.githubusercontent.com/34569466/180225078-70b45345-db1f-4fe0-952c-a8a0ea3e6b4e.png) ![1658410027001](https://user-images.githubusercontent.com/34569466/180225131-9e2177b8-542d-4af3-95b0-27906e7a7d0e.png)

两个地方，一个是nginx中对http访问重定向到https，另一个是博客后台中的博客域名要修改成https开头的。
