### ISSUE TITLE
求助大佬，这两个是要怎么调出来？

### ISSUE THREAD

**Issue by xianweibo** [qinhua/halo-theme-joe2.0#144]
### 是什么版本出现了此问题？

joe2.0

### Halo 版本

halo1.5.3

### 平台

桌面端

### 描述缺陷

求助大佬，这两个是要怎么调出来
![1658410818287](https://user-images.githubusercontent.com/34569466/180228138-b059c6c2-03b1-4b29-9a39-33b54c9d3d87.jpg)
![1658410830550](https://user-images.githubusercontent.com/34569466/180228148-5f54d9d5-e2d7-4100-90a2-b3cba504eacd.png)
？

**Comment by qinhua** [comment]
@xianweibo 主题升级到 V1.0.10 后才有相关功能
