### ISSUE TITLE
后台修改了主题配置后，网站访问不正常，halo java控制台有报错

### ISSUE THREAD

**Issue by nanjunyu** [qinhua/halo-theme-joe2.0#148]
### 是什么版本出现了此问题？

V1.0.10

### Halo 版本

1.6.0-SNAPSHOT

### 平台

桌面端

### 操作系统

macos

### 浏览器

google chome

### 在线站点地址

https://pcias.amestech.cn/collin

### 描述缺陷

网站访问不正常很多转圈圈

### 如何复现

修改了主题配置后出现的，也不知道具体原因，在修改之前是正常访问的。

### 期望结果

网站恢复正常，谢谢了。

### 附加信息

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/23097168/182031416-4cd76a90-97ef-4bd7-a872-e0d4e29309c4.png">

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/23097168/182031466-848206a4-7edd-4178-bb83-c0c51a5b9405.png">

**Comment by qinhua** [comment]
@nanjunyu 看错误提示是某个配置项丢失了，不过看你的网站好像恢复了
