### ISSUE TITLE
文章详情页头像与用户名间距不正常

### ISSUE THREAD

**Issue by Viking602** [qinhua/halo-theme-joe2.0#149]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.5.4

### 平台

桌面端

### 操作系统

Windows

### 浏览器

Chrome

### 在线站点地址

https://blog.dev.vark.fun/s/about

### 描述缺陷

![image](https://user-images.githubusercontent.com/27732503/182910522-f597249e-c4f1-437e-ad63-dc796300ea3e.png)
![image](https://user-images.githubusercontent.com/27732503/182911108-0d94be47-9f28-4d76-b3cb-a29cd82fa322.png)

文章详情页 头像与用户名之间间隔过大

**Comment by qinhua** [comment]
@Viking602 我看你自己在 body 标签中加了一句样式， text-align：center； 这个就导致某些样式也被应用了居中的效果（样式污染），记得放到合适的位置，用 css 选择器来限制作用域。

**Comment by Viking602** [comment]
ok 感谢回复 我这边修改一下

Baby Chin ***@***.***> 于2022年8月5日周五 12:37写道：
