### ISSUE TITLE
文章时间问题

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#15]
大佬，你好！
我这边在更新一篇之前已经发布的文章时，在更新后，看到文章页面的 温馨提示中的更新时间是发布时间。

按我的理解，温馨提示中的时间应该是文章的更新时间吧！

期望：
![image](https://user-images.githubusercontent.com/19606627/141974674-0674b1e4-7977-4994-95e2-5ae072ad4c46.png)

**Comment by qinhua** [comment]
@bxbdba 哈哈，大意了，忘改成 `updateTime` 了，下个版本见

**Comment by qinhua** [comment]
@bxbdba 已修复
