### ISSUE TITLE
文章页面 增加一些设置

### ISSUE THREAD

**Issue by qq547176052** [qinhua/halo-theme-joe2.0#158]
### 你当前使用的版本

2.0

### 你的建议是否涉及到一些现有的问题？

增加文章页面一些用户设置

### 描述你想实现的效果

![建议](https://user-images.githubusercontent.com/26636842/187353765-7e59efe8-4a90-49a7-87b6-8942c283958a.png)

**Comment by qinhua** [comment]
目前设置中有部分是支持的，有些还需要特别支持才可以
