### ISSUE TITLE
代码块样式bug

### ISSUE THREAD

**Issue by kecikeci** [qinhua/halo-theme-joe2.0#16]
**描述缺陷**

bug：所有文章页代码块样式没生效
版本：halo v1.4.13  主题 v1.0.4

![image](https://user-images.githubusercontent.com/32811349/142150488-bcde2fcb-5601-442d-9eeb-ac188359777b.png)
![image](https://user-images.githubusercontent.com/32811349/142150523-cfd5c498-9d26-4fcd-949e-9725cfa9d5fc.png)

请简洁而清晰的描述一下这个缺陷。

**如何复现**

https://4xx.me/archives/94.html

复现步骤如下:

1. 打开 "xxx"
2. 点击 "xxx"
3. 滚动到 "xxx"
4. 发生错误

**期望结果**

简洁而清晰的描述一下你最终期望的结果。

**截图**

如有需要，可以附上一些截图。

**PC 端 (请提供以下信息):**

- 操作系统：[e.g. iOS]
- 浏览器：[e.g. chrome, safari]
- 版本：[e.g. 22]

**移动端 (请提供以下信息):**

- 设备型号：[e.g. iPhone6]
- 操作系统：[e.g. iOS8.1]
- 浏览器：[e.g. stock browser, safari]
- 版本：[e.g. 22]

**额外信息**

可以添加一些额外的对我们处理这个问题有帮助的信息。

**Comment by qinhua** [comment]
@kecikeci 
文章中的代码分 **单行代码** 和 **代码块** 两种，在 `MarkDown` 语法里：

> \`这是单行代码\` 
> 
> \```js
> 这是代码块
> \```

**解答：**

1. 图中这种并不是代码块，而是单行代码，主题目前不对也不计划对单行代码做处理；
2. 至于这种没换行的样式问题我会在接下来的版本修复；
3. 要想渲染代码块请使用正确的格式，也就是 3 个飘号，能手动指定语言最好手动指定语言。

**建议：**

1. 特别长的单行代码直接用代码块形式；
2. 养成良好的书写习惯，后面即使换主题了，也都是可以兼容的，多花点时间，规范一点，博客就美观好看一点。

**Comment by kecikeci** [comment]
> @kecikeci 文章中的代码分 **单行代码** 和 **代码块** 两种，在 `MarkDown` 语法里：
> 
> > `这是单行代码`
> > ```js
> > 这是代码块
> > ```
> 
> **解答：**
> 
> 1. 图中这种并不是代码块，而是单行代码，主题目前不对也不计划对单行代码做处理；
> 2. 至于这种没换行的样式问题我会在接下来的版本修复；
> 3. 要想渲染代码块请使用正确的格式，也就是 3 个飘号，能手动指定语言最好手动指定语言。
> 
> **建议：**
> 
> 1. 特别长的单行代码直接用代码块形式；
> 2. 养成良好的书写习惯，后面即使换主题了，也都是可以兼容的，多花点时间，规范一点，博客就美观好看一点。

![image](https://user-images.githubusercontent.com/32811349/142208409-9395e536-611f-43fb-b128-fff44e418a9b.png)

我这个写的确实是代码块，不知道为什么没有样式？

**Comment by kecikeci** [comment]
还是说必须要加 代码类型 吗？

**Comment by kecikeci** [comment]
![image](https://user-images.githubusercontent.com/32811349/142208798-1c0d9c4a-5e2b-4405-acfb-f053207f22aa.png)

确实是要加类型，可以默认个类型最好。。不过有个小问题，在触摸板左右不能滑动代码块

**Comment by qinhua** [comment]
最好加上类型，高亮会准确一些，我看能不能默认给个类型。

**Comment by qinhua** [comment]
触摸板交互目前没考虑，后面慢点优化，都会有的，目前先保证基本功能。

**Comment by kecikeci** [comment]
> 最好加上类型，高亮会准确一些，我看能不能默认给个类型。

嗯嗯   加个默认类型吧

我试了下  可以加成 text

**Comment by qinhua** [comment]
@kecikeci 已做优化，再试试看
