### ISSUE TITLE
所有页面凭空出现图片，遮挡住内容

### ISSUE THREAD

**Issue by Marvintian518** [qinhua/halo-theme-joe2.0#168]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.5.3

### 平台

桌面端

### 操作系统

windows

### 浏览器

谷歌浏览器

### 在线站点地址

http://www.yinblog.com.cn:8090/

### 描述缺陷

不论哪个页面都有，一个固定的背景图片遮挡在内容上，内容如下
<img width="100%" height="150" src="/themes/joe2.0/source/img/context_bg.png" onerror="Joe.errorImg(this)" alt="文章目录">

### 如何复现

进入首页即可看到

### 期望结果

去掉背景

**Comment by qinhua** [comment]
应该是css缓存导致的
