### ISSUE TITLE
公告标题没有使用主题色

### ISSUE THREAD

**Issue by forrany** [qinhua/halo-theme-joe2.0#169]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.5.4

### 平台

桌面端

### 操作系统

macox

### 在线站点地址

https://vincentko.top

### 描述缺陷

设置了主题色
但是，公告的内容，仍然是之前的颜色
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/29779326/198859750-b3e25bd7-9bb0-4bd1-b496-5c582fb0583d.png">

**Comment by qinhua** [comment]
哈哈，故意的
