### ISSUE TITLE
控制台使用 window.ThemeConfig 会输出配置的api key等其他关键信息

### ISSUE THREAD

**Issue by kecikeci** [qinhua/halo-theme-joe2.0#17]
控制台使用 window.ThemeConfig 会输出配置的api key等其他关键信息

![image](https://user-images.githubusercontent.com/32811349/142154400-cb05804b-2f33-4abc-ba4f-dae4accc79b2.png)

**Comment by qinhua** [comment]
@kecikeci 这里我刻意放出来让大家参考的（因为现在主题功能还不稳定，大家在修改的时候可能需要查看配置信息）。至于你说的 access_key，其实没关系，前端都是明文的，请求头里也有。

还有，这个日志我提供了开关，可以在 `主题配置-其它` 中关闭的。
暂时没计划去掉这个。

**Comment by kecikeci** [comment]
好的   明白了~

**Comment by qinhua** [comment]
最新版本已关闭提示
