### ISSUE TITLE
支持前台显示加密文章

### ISSUE THREAD

**Issue by WakinHuan** [qinhua/halo-theme-joe2.0#173]
### 你当前使用的版本

 1.0.10 

### 你的建议是否涉及到一些现有的问题？

能不能考虑下支持前台显示加密文章

### 描述你想实现的效果

在首页显示加密的文章，但是查看文章一样需要密码

**Comment by qinhua** [comment]
提错项目了，这属于 halo 那边的需求，请参考相关 [issue](https://github.com/halo-dev/halo/issues/2413)
