### ISSUE TITLE
希望增加配置首页精品分类标题位置的选项

### ISSUE THREAD

**Issue by simin-in-tw** [qinhua/halo-theme-joe2.0#174]
### 你当前使用的版本

1.0.10

### 你的建议是否涉及到一些现有的问题？

首页的精品分类默认显示分类的封面图和分类名称，目前封面图位于分类名称下面作为背景图，但是看起来不够美观（标题的文字和我的背景图不搭调）

### 描述你想实现的效果

希望可以添加一个选项，用于设置分类名称位置，例如分类名称位于分类封面图的：上方 / 下方 / 封面图的上层

### 描述一些方案

文章分类页面 (/categories) 的分类名称就是位于封面图下方，这就是我觉得更美观的效果。

**Comment by qinhua** [comment]
@guduguai 这个大可以自己去修改样式，目前不想在这里做过多的自定义配置

**Comment by simin-in-tw** [comment]
> @guduguai 这个大可以自己去修改样式，目前不想在这里做过多的自定义配置

好的，了解。
