### ISSUE TITLE
文章归档页和文章分类页根据分类列表显示树形结构

### ISSUE THREAD

**Issue by simin-in-tw** [qinhua/halo-theme-joe2.0#177]
### 你当前使用的版本

1.0.10

### 你的建议是否涉及到一些现有的问题？

文章归档页和文章分类页展示的分类没有根据分类列表展示树形结构，无法区分子分类归属于哪个上级目录，看起来比较乱。

### 描述你想实现的效果

目前无论是文章归档页还是文章分类页，页面的分类都是没有展示分类结构的，看起来比较乱。希望可以根据分类列表所设定的层级展示树形结构，默认只显示上层目录为根目录的分类，点击上层目录为根目录的分类后才显示子目录。

### 描述一些方案

购物平台的分类模式，例如想买一台电脑，可以在分类列表选择 “数码-电脑-品牌” ，以筛选出自己想要的电脑。

### 附加信息

无

**Comment by qinhua** [comment]
关注新版本

**Comment by simin-in-tw** [comment]
> 关注新版本

OKK
