### ISSUE TITLE
文章无封面图时的匹配顺序

### ISSUE THREAD

**Issue by simin-in-tw** [qinhua/halo-theme-joe2.0#178]
### 你当前使用的版本

1.0.10

### 你的建议是否涉及到一些现有的问题？

在文章没有设置封面图、分类目录有设置封面图的条件下，文章默认显示的是目录的封面图。但是当我为文章设置 “A分类” 和 “B分类” 两个分类时（“A分类” 是 “B分类” 的上级目录），文章默认始终显示 “A分类” 的封面图

### 描述你想实现的效果

当文章没有设置封面图时，如果文章设置多个分类，优先显示子分类的封面图。

### 描述一些方案

修改匹配顺序为：文章封面图→子分类封面图→根目录分类封面图，或添加一个主题配置选项可自定义配置封面图匹配顺序。

**Comment by qinhua** [comment]
这个可能要等新版本去推进

**Comment by simin-in-tw** [comment]
> 这个可能要等新版本去推进

了解，感谢回复。
