### ISSUE TITLE
设置文章默认缺省页面和加载页面后，在搜索栏查询后的结果中没有替换

### ISSUE THREAD

**Issue by yangzeng** [qinhua/halo-theme-joe2.0#18]
**描述缺陷**
在主题中，修改文章默认缩略图后，通过分类，标签和首页跳转进去的页面 都替换了。

但是通过导航栏中的搜索栏目，输入搜索条件后查询到的列表中，页面的默认图没有被替换

**Comment by qinhua** [comment]
@yangzeng 非常感谢你，这个问题我也发现了，确实是搜索页忘记改了。下版本见哈

**Comment by qinhua** [comment]
@yangzeng 已修复

**Comment by yangzeng** [comment]
@qinhua 棒
