### ISSUE TITLE
Edge浏览器首页列表以及轮播图不展示文章的封面图

### ISSUE THREAD

**Issue by YaoLei10430** [qinhua/halo-theme-joe2.0#180]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.6.0

### 平台

桌面端

### 操作系统

windows11 21H2

### 浏览器

Microsoft Edge 版本 107.0.1418.62 (正式版本) (64 位)

### 在线站点地址

https://bbchin.com/

### 描述缺陷

![image](https://user-images.githubusercontent.com/26989826/205534639-6d84c1f2-5c3c-441d-883b-60815e9c8181.png)
![image](https://user-images.githubusercontent.com/26989826/205534813-fc21d40d-1254-4c34-ac13-ba8379c6ab86.png)

**Comment by YaoLei10430** [comment]
浏览器开启了广告拦截插件导致的

**Comment by qinhua** [comment]
@YaoLei10430 可以提供下插件名吗

**Comment by YaoLei10430** [comment]
@qinhua 


> @YaoLei10430 可以提供下插件名吗

[AdGuard 广告拦截器](https://microsoftedge.microsoft.com/addons/detail/adguard-%E5%B9%BF%E5%91%8A%E6%8B%A6%E6%88%AA%E5%99%A8/pdffkfellgipmhklpdmokmckkkfcopbh)
