### ISSUE TITLE
网页推送过程中，提示服务器被百度屏蔽了，请重试！

### ISSUE THREAD

**Issue by MicroMatrixOrg** [qinhua/halo-theme-joe2.0#182]
### 是什么版本出现了此问题？

V1.0.10

### Halo 版本

1.6.1

### 平台

桌面端

### 操作系统

Mac OS

### 浏览器

Chrome

### 在线站点地址

https://micromatrix.eu.org/archives/vue3%E6%BA%90%E7%A0%81%E5%AD%A6%E4%B9%A0-6-%E8%B0%83%E5%BA%A6%E5%99%A8

### 描述缺陷

进入统一篇文章页面都会提示文章未收录，然后推送成功。查看了接口发现`https://bbchin.com/halo-api/bd/iscollect?_r=1671009785311&url=xxxx`，这个接口提示服务器被百度屏蔽了，请重试。
然后后面的`https://bbchin.com/halo-api/bd/push`这个接口好像是成功的

**Comment by forrany** [comment]
地址已经404了~

看了域名你已经转其他博客了呀

**Comment by MicroMatrixOrg** [comment]
> 地址已经404了~
> 
> 看了域名你已经转其他博客了呀

我已经不用Halo了，我目前主要用Gridea+vercle了
