### ISSUE TITLE
求助关于Joe2.0，Halo版本1.6.1里，谷歌广告显示的位置问题

### ISSUE THREAD

**Issue by Lau0x** [qinhua/halo-theme-joe2.0#185]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.6.1

### 平台

桌面端

### 在线站点地址

blog.laoda.de

### 描述缺陷

目前用的博客主题是Joe2.0，Halo版本1.6.1

之前在博客中添加过谷歌广告但是显示的位置有时候是随机的，个别时候还会影响读者阅读，我想要在博客固定的位置显示谷歌广告，比如侧边栏：

![5bbb47bfaf166e19911fb2ffd826a2e2.png](http://img.laoda.de/i/2023/02/11/hd6yh4-2.webp)

或者是文章的列表之间：

![a9b65fcbd14561bf8ea7e97db4c37ab6.png](http://img.laoda.de/i/2023/02/11/hecwzn-2.webp)

我尝试使用了谷歌的信息流广告，

![960e5d9913f01aa01a92a78c5ea5fbed.png](http://img.laoda.de/i/2023/02/11/hd8btg-2.webp)

![78a9ce32c2cec14faf64c84a892f477a.png](http://img.laoda.de/i/2023/02/11/hd9z6a-2.webp)

的确可以选择一个内容模块，让谷歌根据其板式和样式制作一个广告

![1a182c17094dafdf04fc0b4d25fdd9dc.png](http://img.laoda.de/i/2023/02/11/hdb9ew-2.webp)

我获得的代码大致如下：

```js
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8920xxxxxxxx"
     crossorigin="anonymous"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-format="fluid"
     data-ad-layout-key="-fg-3z+a3-5l-co"
     data-ad-client="ca-pub-8920xxxxxxxx"
     data-ad-slot="731929217213"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

![38e764a9c7296191758d8600dcc86d27.png](http://img.laoda.de/i/2023/02/11/hdctfp-2.webp)

随后我将代码插入到Joe主题的如下位置：

![60e9bc8346b6e2951215e6e70eb97515.png](http://img.laoda.de/i/2023/02/11/hde43g-2.webp)

但是广告会显示在页脚：

![6c44373286ef2857987eba385b81ed3f.png](http://img.laoda.de/i/2023/02/11/hdfj8r-2.webp)

想请教一下，是否是我代码位置插入的不对？如果插入不对的话，应该放在那个位置？还有“填入JS代码，无需script标签，将插入body标签尾部” 这边应该怎么理解，我需要把Google Adsense的代码改成什么样子（不太清楚如何去掉script标签 == ）

PS： 我尝试直接把Google Adsense的代码加在“博客设置”的“统计代码”里面，还是和上面一样的效果，广告显示在了页脚，并没有显示在期望的位置。

![e1f0067a7a53f2522106325be88421c6.png](http://img.laoda.de/i/2023/02/11/hdgw8r-2.webp)

先谢谢帮助！

**Comment by qinhua** [comment]
@RalstonLiu 我研究一下

**Comment by Lau0x** [comment]
> @RalstonLiu 我研究一下

好的，辛苦啦

**Comment by qinhua** [comment]
@RalstonLiu 
我试了一下，发现这个广告代码需要您 `手动放置` 在想显示的 `html` 结构中才行，如您上面的操作，那段代码会插入到页面尾部，最后广告自然也就出现在尾部了。（见 [将广告代码放置在 HTML 中的什么位置（广告单元）](https://support.google.com/adsense/answer/9190028)。

您复制的广告代码中那个 `ins` 标签就是占位符，用来告诉 `Google Adsense` 要将广告插入到哪里。所以您只需要把这段放到指定的模板位置即可。
在 Halo 博客中，您可以通过 `后台管理-外观-主题编辑` 功能进行操作，找到相应的模板文件，然后粘贴进去保存即可看到效果。

至于 `script` 标签相关的代码，您需要放置在 `后台管理-外观-主题设置-自定义-外部JS链接（head）` 中。如下图所示：

![screenshot-20230214-144606](https://mblog-1257649495.cos.ap-nanjing.myqcloud.com/mblog/screenshot-20230214-144606.png)
![screenshot-20230214-144432](https://mblog-1257649495.cos.ap-nanjing.myqcloud.com/mblog/screenshot-20230214-144432.png)

### 注意
目前首页的文章列表默认是异步方式获取，内容使用 `js` 拼接而成，你可能需要修改相关源码实现（`source/js/index.js` 中的 `initList` 方法）。
当然，您也可以直接改为后端渲染方式，即关闭异步加载（`后台管理-外观-主题设置-首页-异步加载文章列表`），那样就可以在模板中直接添加 `ins` 代码了（`template/macro/list_index.ftl`）。

目前配置起来确实麻烦，后续可能会开放相关区域广告位的配置入口。

**Comment by Lau0x** [comment]
> @RalstonLiu 我试了一下，发现这个广告代码需要您 `手动放置` 在想显示的 `html` 结构中才行，如您上面的操作，那段代码会插入到页面尾部，最后广告自然也就出现在尾部了。（见 [将广告代码放置在 HTML 中的什么位置（广告单元）](https://support.google.com/adsense/answer/9190028)。
> 
> 您复制的广告代码中那个 `ins` 标签就是占位符，用来告诉 `Google Adsense` 要将广告插入到哪里。所以您只需要把这段放到指定的模板位置即可。 在 Halo 博客中，您可以通过 `后台管理-外观-主题编辑` 功能进行操作，找到相应的模板文件，然后粘贴进去保存即可看到效果。
> 
> 至于 `script` 标签相关的代码，您需要放置在 `后台管理-外观-主题设置-自定义-外部JS链接（head）` 中。如下图所示：
> 
> ![screenshot-20230214-144606](https://camo.githubusercontent.com/8953aa422ff74a178fed2722d7f2e05e6f48e1deacc1b4f119be622bebb331b1/68747470733a2f2f6d626c6f672d313235373634393439352e636f732e61702d6e616e6a696e672e6d7971636c6f75642e636f6d2f6d626c6f672f73637265656e73686f742d32303233303231342d3134343630362e706e67) ![screenshot-20230214-144432](https://camo.githubusercontent.com/0df9dfbfbefc56a049b9be778b14e0cf9f319564a9293204d519212a2f65d1e0/68747470733a2f2f6d626c6f672d313235373634393439352e636f732e61702d6e616e6a696e672e6d7971636c6f75642e636f6d2f6d626c6f672f73637265656e73686f742d32303233303231342d3134343433322e706e67)
> 
> ### 注意
> 目前首页的文章列表默认是异步方式获取，内容使用 `js` 拼接而成，你可能需要修改相关源码实现（`source/js/index.js` 中的 `initList` 方法）。 当然，您也可以直接改为后端渲染方式，即关闭异步加载（`后台管理-外观-主题设置-首页-异步加载文章列表`），那样就可以在模板中直接添加 `ins` 代码了（`template/macro/list_index.ftl`）。
> 
> 目前配置起来确实麻烦，后续可能会开放相关区域广告位的配置入口。

非常感谢这么详细的回答！我去试试！（我找了一圈没找着您的咖啡链接，想要请您喝咖啡，我一直在用您的主题，感觉非常好）

**Comment by qinhua** [comment]
@RalstonLiu 
哈哈，感谢支持
