### ISSUE TITLE
博客首页文章缩略图不显示文章内图片

### ISSUE THREAD

**Issue by train2000** [qinhua/halo-theme-joe2.0#188]
### 是什么版本出现了此问题？

1.0.10

### Halo 版本

1.5.3

### 平台

桌面端

### 在线站点地址

https://it-touch.cn

### 描述缺陷

博客首页文章缩略图不显示文章内图片
![image](https://user-images.githubusercontent.com/81215976/225880495-e7001d6b-83b8-4774-8f2a-ec97f1345c2f.png)
![image](https://user-images.githubusercontent.com/81215976/225880990-80980dbf-f234-4059-8779-a6689a987ac9.png)
![image](https://user-images.githubusercontent.com/81215976/225880777-dde48319-13af-4d93-a484-1075f74619e6.png)

**Comment by qinhua** [comment]
@train2000 缩略图需要单独配置，无法自动读取文章内容中的图片
