### ISSUE TITLE
文章内容页底部显示的标签错误问题

### ISSUE THREAD

**Issue by yangzeng** [qinhua/halo-theme-joe2.0#20]
**描述缺陷**

所有的文章底部的标签，都是固定的获取标签列表的前五个。

查询结果是不对的。Halo本身支持查询当前文章的关联标签：
https://docs.halo.run/developer-guide/theme/template-tag#%E8%8E%B7%E5%8F%96%E6%96%87%E7%AB%A0%E7%9A%84%E6%89%80%E6%9C%89%E6%A0%87%E7%AD%BElistbypostid

**期望结果**
文章应该显示它自己所关联的标签，而不是固定的

**Comment by qinhua** [comment]
ok

**Comment by qinhua** [comment]
@yangzeng 已做调整

**Comment by yangzeng** [comment]
@qinhua  棒
