### ISSUE TITLE
页面上分类显示不全

### ISSUE THREAD

**Issue by kecikeci** [qinhua/halo-theme-joe2.0#21]
后台 文章 配置有多个分类，前台 页面上只显示一个

![image](https://user-images.githubusercontent.com/32811349/142366443-0cb96306-687c-4de2-97a9-66807e060017.png)
![image](https://user-images.githubusercontent.com/32811349/142366492-baf6cbeb-428e-4bfb-afae-0f7d0f9a024e.png)
![image](https://user-images.githubusercontent.com/32811349/142366525-2049b5f5-4c25-473e-b62b-1a4b16d30939.png)

**Comment by qinhua** [comment]
@kecikeci 这是一个已知问题，目前模板标签似乎取不到

**Comment by qinhua** [comment]
列表为了适配只展示第一个的

**Comment by qinhua** [comment]
@kecikeci 这个暂时不影响使用，且涉及到适配，后面有时间再来优化。

**Comment by qinhua** [comment]
@kecikeci `1.0.6` 已支持首页展示全部分类，但鉴于自适应的考虑，移动端只展示一个分类标签，详情页还是只展示一个
