### ISSUE TITLE
进首页时一直会有一个404链接，导致首页感觉加载半天还没加载完

### ISSUE THREAD

**Issue by weizhenyu85** [qinhua/halo-theme-joe2.0#22]
http://cn.gravatar.com/avatar/98f1ed5d8e56cfbedb5be95279bc52c3?s=256&d=mm，该链接也没看到在哪配置关闭或什么设置

**Comment by qinhua** [comment]
你很应该是第一次安装 Halo 博客或者重装后没有在后台设置个人头像，这样后台会给一个默认的头像，也就是这个加载不出来的Gravatar 头像，所以你去后台配置一下头像即可。

主题目前头像读取顺序如下：
后台头像 > 主题内默认头像 > 错误时的默认图

**Comment by weizhenyu85** [comment]
好的，我一直以为是主体那里的头像，现在设置好了，多谢
