### ISSUE TITLE
点击首页中 --推荐文章等标签 文章消失 且无法再次加载进来

### ISSUE THREAD

**Issue by Curllen** [qinhua/halo-theme-joe2.0#24]
**描述缺陷**

请简洁而清晰的描述一下这个缺陷。

**如何复现**

复现步骤如下:

1. 打开 首页
2. 点击 "推荐文章"
3. 发生错误

**期望结果**

简洁而清晰的描述一下你最终期望的结果。

![image](https://user-images.githubusercontent.com/21344176/142603762-e776cb20-5820-4755-82c4-f202af947303.png)

**Comment by qinhua** [comment]
收到

**Comment by qinhua** [comment]
@Curllen 已修复
