### ISSUE TITLE
代码堆叠在一起

### ISSUE THREAD

**Issue by Conserry** [qinhua/halo-theme-joe2.0#26]
当打开代码行号时，代码会没有换行，都堆叠在一起。关闭之后就好了。
像这样：
![image](https://user-images.githubusercontent.com/94542535/142747600-248cc788-079a-4f8d-b7f6-b16a49776396.png)
![image](https://user-images.githubusercontent.com/94542535/142747614-e994ae89-ef32-44ec-b5cb-f8895d9b96ab.png)

**Comment by qinhua** [comment]
@Conserry 哈哈😆，1.5版本修缺陷时样式影响了，后面更新后 `cdn` 缓存去不掉，可以等 1.6 版本。
急的话，可以去 `主题设置-其它` 中关闭 `从 CDN 加载静态资源`。

**Comment by Conserry** [comment]
> @Conserry 哈哈😆，1.5版本修缺陷时样式影响了，后面更新后 `cdn` 缓存去不掉，可以等 1.6 版本。 急的话，可以去 `主题设置-其它` 中关闭 `从 CDN 加载静态资源`。

haha，多谢大佬！
