### ISSUE TITLE
文章封面图 不存在的情况下，建议取分类封面图。如果任然没有再随机图

### ISSUE THREAD

**Issue by yangzeng** [qinhua/halo-theme-joe2.0#27]
如果能够在文章没有封面的情况下。默认取文章所属分类的图片，如果还是没有，就取默认图。

比较适合已经写了不少文章的小伙伴使用主题时，节省封面图片的修改工作。

避免文章列表，整版都是一样的图片默认图。

**Comment by qinhua** [comment]
@yangzeng 了不起的建议 👍

**Comment by qinhua** [comment]
@yangzeng `1.0.6` 已支持，现在封面取值逻辑如下：

```
文章封面 > 分类封面 > 标签封面 > 随机图(若开启) > 默认封面
```
