### ISSUE TITLE
cdn问题

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#29]
本次1.0.5版本更新后，发现首页中有个接口会报404，接口如下：
https://cdn.jsdelivr.net/gh/qinhua/halo-theme-joe2.0@1.0.3/source/lib/j-marked/marked.min.js

更新方式：
我这边使用的是Halo的【从主题包更新】，更新后就报错了。

**Comment by qinhua** [comment]
@bxbdba 哥哥，这是缓存啊，也就是你更新主题后，主题配置中还有缓存，你可以看到地址中的版本号还是 `1.0.3` ，而用的是 `1.0.5`。
我昨天更新了 `1.0.5`，线上没这个问题，控制台很干净，你可以去看看 https://bbchin.com。

> 目前没什么好方法，从主题包更新后，我的做法是先切换到其他主题，然后在切换回来的，这样再打开浏览器强刷一下就好了。

补充一下：`1.0.5` 代码块和评论组件的表情解析还有问题，请知悉。

😔 等着后面看会不会好。

**Comment by bxbdba** [comment]
好的！
我重新改了主题又改回来，的确好了。
