### ISSUE TITLE
Content API 设置建议

### ISSUE THREAD

**Issue by IILee5** [qinhua/halo-theme-joe2.0#3]
![image](https://user-images.githubusercontent.com/40862062/141308017-729a65ca-74c7-4b4b-b9c0-f54ad683c526.png)
建议将此处的`Access key`更换为用户后台的配置。不然那些使用了此`Access key`制作小程序的用户全都无法使用这个主题了。
![image](https://user-images.githubusercontent.com/40862062/141308325-8271f6c1-27e2-4f2e-99e8-8b81ff59b55f.png)
可以考虑使用[开发者选项/系统变量]来自定义`Access key`，或者直接在主题配置里面写死也可以的。
感谢作者制作处这么牛的主题！

**Comment by qinhua** [comment]
@IILee5 目前其实是直接读取的后台配置中的 Access key，并不是固定的 `joe2.0`，所以 Access key 随意设置即可。

**Comment by IILee5** [comment]
> @IILee5 目前其实是直接读取的后台配置中的 Access key，并不是固定的 `joe2.0`，所以 Access key 随意设置即可。

这个`Access key`是需要在源代码里面改一下吗

**Comment by qinhua** [comment]
@IILee5 不用改，源码里直接是使用 `options.access_key` 来获取的，没有设置才会用 `joe2.0`。

`'${options.api_access_key!"joe2.0"}'`

可以通过请求头中的 `api-authorization` 来验证。
BTW， `README` 文件我晚点更新一下

**Comment by IILee5** [comment]
那我的文章为啥读不出来T.T  一直显示加载中

**Comment by qinhua** [comment]
@IILee5 那 F12 看下控制台的接口返回的是什么？

**Comment by IILee5** [comment]
@qinhua 错误如下，好像是权限不太对
![image](https://user-images.githubusercontent.com/40862062/141426148-6bf572e1-b265-4e55-ab9a-8d47b7002621.png)
发送的key好像是默认的
![image](https://user-images.githubusercontent.com/40862062/141426254-92fd61fd-3eaf-4316-931f-b345e73d3356.png)

**Comment by qinhua** [comment]
@IILee5 哪个版本的 `halo`，怀疑模板没取到后台的配置用了默认的

**Comment by qinhua** [comment]
先试试后台配成 `joe2.0` 能不能加载出来

**Comment by IILee5** [comment]
环境信息如下
![image](https://user-images.githubusercontent.com/40862062/141432775-013e7209-17da-4c4b-b3fe-b3ac42135073.png)

**Comment by qinhua** [comment]
我用的 `1.4.11` 开发好像可以取到，这个问题我晚点试着复现一下看看哈。

**Comment by IILee5** [comment]
好的好的，辛苦大佬

**Comment by qinhua** [comment]
@IILee5 我试了一下，也问了 Ryan 大佬，目前无法在前台获取后台设置的 `api_access_key`。
所以我会在下个小版本提供一个主题内配置，用来同步后台的 `Access Key` 这样即可解决你的问题。

**Comment by qinhua** [comment]
@IILee5 1.0.2 中已添加 `AccessKey` 的设置项，可用来同步后台配置的 `Access Key` ，你的问题应该可以解决了。👌

**Comment by IILee5** [comment]
刚刚试了一下，已经可以了，感谢大佬～
