### ISSUE TITLE
最新版本更新后，造成的代码显示区域高度错误问题

### ISSUE THREAD

**Issue by yangzeng** [qinhua/halo-theme-joe2.0#30]
更新最新主题风格后，发现所有的代码块的高度都显示不正确了。

主题配置中没有开启代码折叠，结果显示的代码块中，全部的换行都丢失了
效果图
![image](https://user-images.githubusercontent.com/6871017/142817089-de947b06-fa8c-40dd-926d-eca49ffbf552.png)

以为是自身问题，访问大佬你的网页上也是显示的错误。

![image](https://user-images.githubusercontent.com/6871017/142817161-37a6ba77-627c-4b08-9154-98049971d1e1.png)

**Comment by yangzeng** [comment]
找到了介绍说明： https://github.com/qinhua/halo-theme-joe2.0/issues/26 和这个问题一样。

暂时通过关闭代码行数解决，等待之后的1.6.0版本

**Comment by qinhua** [comment]
嗯，我改错了样式，1.0.6 会恢复
