### ISSUE TITLE
文章缩略图存在问题

### ISSUE THREAD

**Issue by qinweizhao** [qinhua/halo-theme-joe2.0#31]
**描述缺陷**

文章缩略图设置为关闭时，搜索的结果显示有缩略图

**如何复现**

复现步骤如下:

1. 主题设置为关闭文章缩略图，首页文章不显示文章缩略图（正常）
2. 在搜索栏中搜索，显示的文章却依然有缩略图

**期望结果**

简洁而清晰的描述一下你最终期望的结果。

**截图**
![image](https://user-images.githubusercontent.com/65989648/142963204-ce17a5d1-49fd-4d44-b786-1c785933a858.png)
![image](https://user-images.githubusercontent.com/65989648/142963019-46f4d559-2b8f-4909-91e1-94587b24f986.png)

**Comment by qinhua** [comment]
目前确实是这样的，只控制了首页列表的缩略图，1.0.6 版本会同步更改。

**Comment by qinhua** [comment]
@qinweizhao 1.0.6已处理
