### ISSUE TITLE
文章页面疑似内容过多时。造成右侧侧边栏显示错位

### ISSUE THREAD

**Issue by yangzeng** [qinhua/halo-theme-joe2.0#32]
**描述缺陷**

内容过长的情况下，右侧 侧边栏换行到底部显示了。

*如何复现**

可以访问一下我的网站的链接：https://zinyan.com/?p=28

**期望结果**

不应该挤占右侧的 侧边栏显示。

**截图**

![image](https://user-images.githubusercontent.com/6871017/143004496-b0fd01b6-5463-4347-bb6e-3e232cb4f76a.png)

**Comment by qinhua** [comment]
@yangzeng 俺刚才对比了一下本人网站和贵网站的同一个页面。
> 版本都是 1.0.5，chrome 浏览器。
奇怪的发现您的文章详情页的 `html` 结构和在下完全不一样，整个文章页的结构完全散了，而且很多页面都有严重的样式问题，我有点不理解的是就算是兼容性问题，页面结构为什么会变？

**Comment by qinhua** [comment]
我看了一下您这篇文章内容，可能是里面有一些特殊字符导致 `html` 标签没有闭合，自己检查一下看看

**Comment by qinhua** [comment]
> 有些内容是我使用过程之中根据使用进行翻译的，有些是通过官网介绍进行直接翻译的。可能有疏漏之处，敬请谅解。

俺又看了一下，发现末尾的这段文字处出现了 **孤独标签**，导致底部的评论和右侧侧边栏被包含到了文章内容的结构中，失去了原有的结构，样式自然就乱了。我看您的其他文章都是正常的。那这种文章内容不规范情况只能靠您自己了，看是不是最近更新改漏了 😆。

您也可以提供原文内容，以便我本地测试，以便快速帮您解决烦恼哦 🤝。

**Comment by yangzeng** [comment]
的确是因为标签造成的问题。

我一开始是在CSDN上发布的。直接从CSDN的编辑页面拷贝的内容，结果出现了部分的指令未能拷贝造成。

问题已经解决了，感谢提供的参考和建议。🤝
