### ISSUE TITLE
代码块格式化问题

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#33]
代码块中的代码格式出现问题。

复现步骤：
1、随便创建一篇博客，使用多行代码块。
2、书写多行对应代码。
3、预览或发布博客。
4、看到代码块行号正常，但是代码块中的代码格式出现问题。

- 操作系统：win 10
- 浏览器：谷歌浏览器
- 版本：97.0.4692.20（正式版本） （64 位）

**Comment by yangzeng** [comment]
#26
你可以先去掉行号显示。 1.0.6版本会修复

**Comment by qinhua** [comment]
@bxbdba 1.0.6已处理
