### ISSUE TITLE
上传halo博客出问题

### ISSUE THREAD

**Issue by fcm339** [qinhua/halo-theme-joe2.0#34]
本地上传到halo会报这个错误 String index out of range: -7，远程获取也不了

**Comment by qinhua** [comment]
@fcm339 有具体错误日志吗，请提供一下具体的参考

**Comment by fcm339** [comment]
控制台没错误日志

**Comment by qinhua** [comment]
是页面报错，还是后台管理系统报错

**Comment by qinhua** [comment]
这个需要提供详细的后台日志信息来排查原因。请参考 [如何查看博客后台日志](https://github.com/qinhua/halo-theme-joe2.0#9%E5%A6%82%E4%BD%95%E6%9F%A5%E7%9C%8B%E5%8D%9A%E5%AE%A2%E5%90%8E%E5%8F%B0%E6%97%A5%E5%BF%97)

**Comment by qinhua** [comment]
@fcm339 期待您的回复

**Comment by fcm339** [comment]
我在本地调试的，日志会看，系统后台实时日志也没报错，应该是哪个参数的问题，不能存入数据库

**Comment by qinhua** [comment]
上传其他主题试试看会不会报错，其实在本地不需要传主题，直接放在相应目录下就可以读取了。

**Comment by fcm339** [comment]
我更新博客版本，现在可以了，谢谢大哥

**Comment by qinhua** [comment]
OK
