### ISSUE TITLE
建议异步加载文章添加文章排序的选项，并非默认的按时间排序

### ISSUE THREAD

**Issue by yumuing** [qinhua/halo-theme-joe2.0#36]
**你的建议是否涉及到一些现有的问题? 请描述清楚**

无

**描述你想实现的效果**

建议首页异步加载文章的场景下，添加文章排序的选项。

**描述一些方案**

增加排序选项

**额外信息**

无

**Comment by qinhua** [comment]
已有相关计划，但异步加载的排序不会在主体内做选项，而是直接在前台使用 `Tab` 切换，这样会更直观一些。

**Comment by qinhua** [comment]
@yumuing 1.0.6已支持在前台切换
