### ISSUE TITLE
使用halo提供的hexo文章导入工具所导入的文章不能被ajax加载显示

### ISSUE THREAD

**Issue by wan-zihao** [qinhua/halo-theme-joe2.0#39]
**描述缺陷**

使用halo提供的hexo文章导入工具所导入的文章不能被ajax加载显示，而通过后台发布的文章没有问题
如果关闭ajax使用后台渲染文章则没有问题

**截图**

这是开启ajax的效果
![image-20211130002634117](https://gitee.com/amazing-feather/images/raw/master/20211130002634.png)
这是关闭ajax的效果
![image-20211130003553834](https://gitee.com/amazing-feather/images/raw/master/20211130003553.png)

**PC 端 (请提供以下信息):**

- Halo 版本：1.4.13
- 操作系统：win10
- 浏览器：chrome

**Comment by qinhua** [comment]
@wan-zihao 很感谢您提供的线索，我想问下前台页面是否有报错，还有是否可以提供相应日志信息。

**Comment by wan-zihao** [comment]
作者你好，下面是前台报的错

至于日志信息，我不知道如何提供，我使用的是docker部署的halo




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinhua/halo-theme-joe2.0"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 下午2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinhua/halo-theme-joe2.0] 使用halo提供的hexo文章导入工具所导入的文章不能被ajax加载显示 (Issue #39)





 
@wan-zihao 很感谢您提供的线索，我想问下前台页面是否有报错，还有是否可以提供相应日志信息。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qinhua** [comment]
这个可能也是缺失参数导致了400，然后前端没取到数据导致的。

**Comment by qinhua** [comment]
这个问题，我下个版本试着做下兼容

**Comment by qinhua** [comment]
@wan-zihao 1.0.8 已处理这个问题
