### ISSUE TITLE
切换深色模式后没有效果，还是和浅色一样，怎么解决？

### ISSUE THREAD

**Issue by obiteaaron** [qinhua/halo-theme-joe2.0#4]
![image](https://user-images.githubusercontent.com/7861389/141401835-dd531734-1da1-4318-90c3-2d147d464203.png)

**Comment by qinhua** [comment]
@obiteaaron 收到，这里目前确实有个策略，就是用户手动点击页面上的模式切换之后，在一天之内都会使用最后设置的模式，而忽略后台的配置。所以目前的解决方式是清空本地存储即可。
> 主要是处理用户手动切换主题后，到底以本地的主题为准还是后台的配置为准。

这个问题我下个版本处理一下，改变一下策略，当后台和本地模式不一致时以后台设置为准。

**Comment by qinhua** [comment]
@obiteaaron 1.0.2 中已处理这个问题，主题模式设置中新增了 `用户模式` 来处理这个交互 👌
