### ISSUE TITLE
安装之后访问提示：请求字段缺失，类型为 String，名称为 keyword

### ISSUE THREAD

**Issue by huasio** [qinhua/halo-theme-joe2.0#40]
**描述缺陷**

安装这个主题之后，仅设置了 Content API，然后直接访问首页，出现：`请求字段缺失，类型为 String，名称为 keyword。`

看了请求，是加载文章数据出现的问题。

我看了上一个 bug，发现关闭 ajax 异步加载文章列表，是可以正常访问的，但是此问题非 hexo 导入的文章引起的，我这里没有使用过导入文章的功能。

**如何复现**

复现步骤如下:

直接访问首页，就弹出错误信息。

**截图**
错误提示信息：
![image](https://user-images.githubusercontent.com/23445537/144020892-a9ff8059-6fe8-43fd-a4be-3ce90fa04115.png)
![image](https://user-images.githubusercontent.com/23445537/144021124-589c067f-9467-4c1d-868f-afa7b69577d0.png)

请求信息：
![image](https://user-images.githubusercontent.com/23445537/144021277-e05bbfa2-f68d-43cf-b03d-4ffe1b6ac7ff.png)
![image](https://user-images.githubusercontent.com/23445537/144021304-07ec11ed-6688-45f1-862d-c7288b28a1a6.png)

错误日志：
![image](https://user-images.githubusercontent.com/23445537/144021891-79bc3a2f-8043-4a3e-a8eb-251710e5da42.png)

如有需要，可以附上一些截图。

**PC 端 (请提供以下信息):**

- Halo 版本：1.4.10
- 操作系统：Windows
- 数据库：MySQL 5.7.28
- 浏览器：Chrome/96.0.4664.45

**额外信息**

我的站点：https://huasio.com

**Comment by qinhua** [comment]
主题是基于 `Halo 1.4.11` 开发的，这个问题是由于 `1.4.10` 中，`keyword` 和 `categoryId` 这两个字段必传导致的。建议升级一下 Halo 到 `1.4.11+`

**Comment by huasio** [comment]
> 主题是基于 `Halo 1.4.11` 开发的，这个问题是由于 `1.4.10` 中，`keyword` 和 `categoryId` 这两个字段必传导致的。建议升级一下 Halo 到 `1.4.11+`

好的，谢谢大佬。

**Comment by qinhua** [comment]
```java
   /**
     * Enable users search published articles with keywords
     *
     * @param pageable store the priority of the sort algorithm
     * @param keyword search articles with keyword
     * @param categoryId search articles with categoryId
     * @return published articles that contains keywords and specific categoryId
     */
    @GetMapping
    @ApiOperation("Lists posts")
    public Page<PostListVO> pageBy(
        @PageableDefault(sort = {"topPriority", "createTime"}, direction = DESC) Pageable pageable,
        @RequestParam(value = "keyword", required = false) String keyword,
        @RequestParam(value = "categoryId", required = false) Integer categoryId) {
        PostQuery postQuery = new PostQuery();
        postQuery.setKeyword(keyword);
        postQuery.setCategoryId(categoryId);
        postQuery.setStatus(PostStatus.PUBLISHED);
        Page<Post> postPage = postService.pageBy(postQuery, pageable);
        return postService.convertToListVo(postPage, true);
    }
```

**Comment by Blackmesa-Canteen** [comment]
谢谢大佬们,很有帮助!

**Comment by huasio** [comment]
升级到 1.4.11+ 就没这个问题了，版本兼容问题。
