### ISSUE TITLE
电脑端图片访问正常，手机浏览器图片无法访问。

### ISSUE THREAD

**Issue by huasio** [qinhua/halo-theme-joe2.0#41]
**描述缺陷**

电脑端使用 chrome 浏览器访问站点，图片正常显示。
手机浏览器访问站点，图片无法显示。

**PC 端 (请提供以下信息):**

- Halo 版本：1.4.10
- 操作系统：Windows
- 浏览器：Chrome 版本 96.0.4664.45（正式版本） （64 位）

**移动端 (请提供以下信息):**

- Halo 版本：1.4.10
- 设备型号：安卓
- 操作系统：鸿蒙 2.0
- 浏览器：夸克
- 版本：最新版

**额外信息**

如果无法复现，建议访问的站点。

我的站点：https://huasio.com

**Comment by qinhua** [comment]
@我这边用手机访问是正常的，可以分析一下那些不展示的图片的请求头信息，看是否是由于一些策略导致的，或者也可以提供出来，咱们一起谈论看看。

**Comment by huasio** [comment]
> @我这边用手机访问是正常的，可以分析一下那些不展示的图片的请求头信息，看是否是由于一些策略导致的，或者也可以提供出来，咱们一起谈论看看。

我刚刚下载了几个手机浏览器，只有夸克会。夸克浏览器没有开发者模式，我不知道移动端有什么软件可以抓包。

**Comment by qinhua** [comment]
抓包用 Fiddler、Charles、Whistle 都可以，直接代理到电脑网络。

**Comment by huasio** [comment]
> 抓包用 Fiddler、Charles、Whistle 都可以，直接代理到电脑网络。

好的，我自己先调试下。

**Comment by qinhua** [comment]
@huasio 不知道你最后找到原因没有
