### ISSUE TITLE
复制时追加的版权文案作者为m酷，默认不从后台获取博主名称，不知从何更改！

### ISSUE THREAD

**Issue by yumuing** [qinhua/halo-theme-joe2.0#42]
![image](https://user-images.githubusercontent.com/77838031/144074347-94deeec5-5143-4617-9c87-5a61db4bc409.png)

**Comment by yangzeng** [comment]
临时解决方案：

1. 在开启复制时追加版权说明时。 下面有一个输入框，你可以自定义你需要展示的版权介绍。
这段介绍会替换js上的默认版权介绍。---简单快捷

2.自己修改主题里面的js文件。路径：source/js/joe.post.js 
 找到里面的initCopy() 函数，修改里面的内容就可以了。  只是这种修改后需要关闭主题配置中的cdn加速。否则无法生效。

**Comment by qinhua** [comment]
好，这里应该是漏掉了

**Comment by qinhua** [comment]
@yumuing 已修复
