### ISSUE TITLE
1.0.7配置博客运行时间后，不能正确展示

### ISSUE THREAD

**Issue by wangshuai0822** [qinhua/halo-theme-joe2.0#45]

**Comment by qinhua** [comment]
@wangshuai0822 具体是什么现象

**Comment by wangshuai0822** [comment]
运行时间

**Comment by wangshuai0822** [comment]
已运行 00 天 00 时 00 分 00 秒 具体报错 ：

**Comment by wangshuai0822** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.initBirthday (joe.common.min.js?v=1.0.5:1)
    at joe.common.min.js?v=1.0.5:1
    at Array.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (joe.common.min.js?v=1.0.5:1)

**Comment by qinhua** [comment]
缓存问题，要先清下主题缓存，怎么还在请求 1.0.5 的 js

**Comment by qinhua** [comment]
@wangshuai0822 每次更新主题后，一定要先切到其他主题在切回来，然后浏览器 Ctrl + F5 刷新，不然缓存会导致很多问题

**Comment by wangshuai0822** [comment]
原来如此，已解决。3q~

**Comment by qinhua** [comment]
ok
