### ISSUE TITLE
文章详情中内容会溢出

### ISSUE THREAD

**Issue by BigBigTimberWolf** [qinhua/halo-theme-joe2.0#46]
**描述缺陷**

在文章详情中插入代码段，如果代码段很长，就会溢出内容区域

**如何复现**

复现步骤如下:
新建一个博客，插入代码段，不指定代码类型，内容要足够的长，如：
```
http://localhost:9096/authorize?client_id=test_client_1&response_type=code&scope=all&state=xyz&redirect_uri=http://localhost:9093/cb
```

**期望结果**
给个默认的txt渲染或者别的类型的渲染

**截图**

![image](https://user-images.githubusercontent.com/43033702/144794256-3b48e9d3-fe0b-46de-9fb8-494680ae80b6.png)

**PC 端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.13]
- 操作系统：[e.g. MAC]
- 浏览器：[e.g. chrome]

**Comment by qinhua** [comment]
长内容应该用代码块
```
你的内容
```

**Comment by qinhua** [comment]
请升级最新版本使用
