### ISSUE TITLE
访问首页后台有报错，具体报错如下

### ISSUE THREAD

**Issue by barry200890** [qinhua/halo-theme-joe2.0#48]
**描述缺陷**
Authentication failure: [API has been disabled by blogger currently], status: [403 FORBIDDEN], data: [null]
请简洁而清晰的描述一下这个缺陷。

**如何复现**
本地开发欢迎测试，直接安装完主题后，进博客首页报api has been disabled by blogger curently.
复现步骤如下:

1. 打开 "xxx"
2. 点击 "xxx"
3. 滚动到 "xxx"
4. 发生错误

**期望结果**

简洁而清晰的描述一下你最终期望的结果。

**截图**
![image](https://user-images.githubusercontent.com/65383345/145179813-c6180bf8-2dbd-4953-9bc3-ef121e28a2ef.png)

如有需要，可以附上一些截图。

**PC 端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.2]
- 操作系统：[e.g. iOS]
- 浏览器：[e.g. chrome, safari]
- 版本：[e.g. 22]

**移动端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.2]
- 设备型号：[e.g. iPhone6]
- 操作系统：[e.g. iOS8.1]
- 浏览器：[e.g. stock browser, safari]
- 版本：[e.g. 22]

**额外信息**

可以添加一些额外的对我们处理这个问题有帮助的信息。

**Comment by qinhua** [comment]
请查看 [主题使用文档](qinhua.github.io/halo-theme-joe2.0) 解决

**Comment by qinhua** [comment]
> > 
> 
> 点开就是 Not Found

再试试，昨天写错了，对不起
