### ISSUE TITLE
推荐列表没有推荐文章显示

### ISSUE THREAD

**Issue by AmazingK64** [qinhua/halo-theme-joe2.0#49]
已检查主题与系统设置的Access Key是否保存一致
首页报错如下图
![image](https://user-images.githubusercontent.com/74052767/145317503-c6a045ac-4658-45e1-a234-f2498c7898c6.png)

**Comment by qinhua** [comment]
@AmazingK64 您好，请提供站点地址协助我排查。

**Comment by AmazingK64** [comment]
amazingk.cn
我去把主题换过来

**Comment by AmazingK64** [comment]
> @AmazingK64 您好，请提供站点地址协助我排查。

请问推荐文章是自动按发布时间排序吗，我在主题设置中没有看到相关的说明

**Comment by qinhua** [comment]
创建时间倒序，置顶优先

**Comment by qinhua** [comment]
@qinhua 报错的问题需要升级主题到最新版本 1.0.7 解决，这个是以前的一个问题，因为网站标题，K'Blog 中有个 ’ 没转义导致的。

**Comment by AmazingK64** [comment]
问题已解决，升级主题后就有显示了，谢谢
