### ISSUE TITLE
单行代码复制问题

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#5]
大佬，你好！
是这样，目前我使用大佬的主题发现在单行代码操作，单击是直接复制整行，是否能够正常的选中内容去复制？

**Comment by qinhua** [comment]
🙃 嗨，这里之前我做了一个简化，鼠标点击就会全选，想着都是简单的单词，不用手动再去选，使用的 `user-select: all；` 来控制的，看来是多余了。
可以的，这个可以下个小版本去掉。

**Comment by bxbdba** [comment]
好的！
谢谢大佬！

**Comment by qinhua** [comment]
@bxbdba 1.0.2 中增加了单行代码块的点击选中开关，默认关闭。

**Comment by bxbdba** [comment]
大佬辛苦了！凌晨还在改
