### ISSUE TITLE
主题cdn引入404

### ISSUE THREAD

**Issue by Alone7707** [qinhua/halo-theme-joe2.0#50]
**描述缺陷**

使用该主题控制台报cdn引入的资源文件404
是不是cdn地址更换了？

**如何复现**

复现步骤如下:

1. 打开 "xxx"
2. 点击 "xxx"
3. 滚动到 "xxx"
4. 发生错误

**期望结果**

尽快修复或望可告知解决方法

**截图**

![image](https://user-images.githubusercontent.com/63057446/145368253-cbbd796d-856a-4341-9f2d-1b9ac0b46d86.png)

**PC 端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.11]
- 操作系统：[e.g. iOS]
- 浏览器：[e.g. chrome, safari]
- 版本：[e.g. 22]

**移动端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.11]
- 设备型号：[e.g. iPhone6]
- 操作系统：[e.g. iOS8.1]
- 浏览器：[e.g. stock browser, safari]
- 版本：[e.g. 22]

**额外信息**

可以添加一些额外的对我们处理这个问题有帮助的信息。

**Comment by qinhua** [comment]
应该是更新主题后没清缓存

**Comment by Alone7707** [comment]
> 应该是更新主题后没清缓存

缓存怎么请呢，在后台没找到，是要在服务器删除哪个文件吗？

**Comment by qinhua** [comment]
文档里有写

**Comment by Alone7707** [comment]
> 文档里有写

好的，谢谢回答
