### ISSUE TITLE
归档页面使用分页的方式。

### ISSUE THREAD

**Issue by ruibaby** [qinhua/halo-theme-joe2.0#52]
**描述缺陷**

目前没有分页，会导致在文章量较多的时候出现性能问题。

**如何复现**

复现步骤如下:

无

**期望结果**

使用：https://docs.halo.run/developer-guide/theme/page-variable#archiveslist

**截图**

无

**PC 端 (请提供以下信息):**

- Halo 版本：1.4.15
- 操作系统：macOS
- 浏览器：Edge
- 版本：latest

**移动端 (请提供以下信息):**

无

**额外信息**

无

**Comment by qinhua** [comment]
@ruibaby 哥，是不是现在这种通过 `<@postTag method="archive" type="year">` 获取的方式不支持分页，只有 `<#list posts.content as post>` 这种才支持？

**Comment by ruibaby** [comment]
@qinhua 可以参考一下这个哦。https://github.com/halo-dev/halo-theme-anatole/blob/master/archives.ftl

**Comment by ruibaby** [comment]
> @ruibaby 哥，是不是现在这种通过 `<@postTag method="archive" type="year">` 获取的方式不支持分页，只有 `<#list posts.content as post>` 这种才支持？

是的，自定义标签没有提供分页的方法。

**Comment by qinhua** [comment]
那我做个类型切换的开关吧，时间轴和普通列表2种

**Comment by qinhua** [comment]
@ruibaby 1.0.8 已添加分页
