### ISSUE TITLE
移动端布局缺陷

### ISSUE THREAD

**Issue by Hih314** [qinhua/halo-theme-joe2.0#53]
**描述缺陷**
移动端发布图片时，图片偏右显示
**如何复现**

复现步骤如下:

1. 打开 "附有图片的页面"
2. 图片偏右显示

**期望结果**

布局调整

**截图**

![image](https://user-images.githubusercontent.com/76816419/145664399-09f4bb8e-4297-4425-92b8-3e40d99ba416.png)

**移动端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.15]
- 设备型号：[e.g. oppo find x3]
- 操作系统：[e.g. Android 12]
- 浏览器：[e.g. stock browser, safari]
- 版本：[e.g. 22]

**Comment by qinhua** [comment]
@Hih314 首先，很感谢您对主题的贡献。
但是我们这边网站没遇到这个问题，可能是兼容性问题。
您可以提供自己网站地址，以便协助我们帮您解决。

**Comment by Hih314** [comment]
[https://bubblestorm.top/](url)
**非常感谢！**

**Comment by qinhua** [comment]
@Hih314 把首行缩进关闭就好了，这个会影响

**Comment by Hih314** [comment]
嗯嗯，谢谢 @qinhua
