### ISSUE TITLE
在首页中无意点击到：“精品分类” 出现错误提示： Internal Server Error

### ISSUE THREAD

**Issue by Zinyan-Z** [qinhua/halo-theme-joe2.0#56]
**描述缺陷**

在主题首页中， 轮播图下的 精品分类文字时 无意点击中，发现出现了错误。

以为是自己哪些地方没有配置。后面在博主的网站 https://bbchin.com/ 上点击也出现了相同的问题。

**实现步骤**
1.页面加载完毕后，点击第一次才会出现，再次点击的时候就不会出现了。

2.刷新页面后再次点击可以重现。

**期望结果**

这个地方看鼠标状态，是不支持点击才对。

**截图**

![image](https://user-images.githubusercontent.com/6871017/145744791-bce9522a-d0c1-453e-af9c-e65a20dcd721.png)

**Comment by qinhua** [comment]
收到

**Comment by qinhua** [comment]
点错了，哈哈

**Comment by qinhua** [comment]
@Zinyan-Z V1.0.9 已修复
