### ISSUE TITLE
访问首页报错

### ISSUE THREAD

**Issue by XM2510136957** [qinhua/halo-theme-joe2.0#57]
访问首页弹出
![image](https://user-images.githubusercontent.com/18229485/145954001-9d2dddc8-32bb-4659-a3c1-ad9fddfdd116.png)

**Comment by XM2510136957** [comment]
Access Key 用于页面中 Content API 的校验，不填会导致接口报错，默认为 joe2.0，但可以自己定义，请不要填写中文或特殊字符（请务必同时配置此处的 Access Key 和后台管理中的 Access Key，并保持一致）

???在系统哪里找的 Access Key我没发现

**Comment by qinhua** [comment]
请看文档
