### ISSUE TITLE
留言页等自定义页面可以让用户选择。

### ISSUE THREAD

**Issue by ruibaby** [qinhua/halo-theme-joe2.0#58]
**你的建议是否涉及到一些现有的问题? 请描述清楚**

无

**描述你想实现的效果**

留言页等自定义页面可以让用户选择。

**描述一些方案**

> 目前主题中的留言页面是自定义页面，所以需要你进入 后台管理-页面 ，点击 新建页面 添加留言页，然后把主题目录中 leaving.ftl 的内容复制进去（注释不需要复制），最后进入 外观-菜单 添加刚才自定义的留言页，保存后刷新前台页面即可，其他自定义页面同理。

其实可以命名为 sheet_leaving.ftl，这样的话，用户在新建自定义页面的时候就可以直接选择这个模板了。

**额外信息**

![image](https://user-images.githubusercontent.com/21301288/145971479-fddc353d-fa9b-44d9-8854-c7add78a5e62.png)

![image](https://user-images.githubusercontent.com/21301288/145971535-8a5cccd0-6bdd-4a97-9807-d2985c91da69.png)

**Comment by qinhua** [comment]
@ruibaby 这个太棒了，之前不知道这个，这就可以满足他们创建空白页面的需求啦，哈哈

**Comment by qinhua** [comment]
@ruibaby V1.0.9 已支持
