### ISSUE TITLE
博客置顶问题

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#6]
大佬！
想知道推荐文章这个是随机的吗？是这样，我之前有设置一篇文章的置顶，但是发现在推荐页面没有看到置顶的文章。

是不是推荐文章也要考虑到置顶的情况还是新增模块来增加置顶的文章。

**Comment by qinhua** [comment]
@bxbdba 目前按时间来排序的，你说的可以考虑一下

**Comment by qinhua** [comment]
@bxbdba 1.0.2 中已处理置顶文章的问题 👌

**Comment by bxbdba** [comment]
大佬辛苦了！
