### ISSUE TITLE
博主信息栏相关建议

### ISSUE THREAD

**Issue by qinweizhao** [qinhua/halo-theme-joe2.0#60]
![742](https://user-images.githubusercontent.com/65989648/146323238-5c43cc7d-61fa-4abd-96a0-1e4613f07305.png)

建议这个做成可配置的，或者将评论量改为分类数。

**Comment by qinhua** [comment]
@qinweizhao 收到，这里确实需要优化一下。

**Comment by qinhua** [comment]
@qinweizhao V1.0.9 已做处理，但目前也只是约定大于配置的形式
