### ISSUE TITLE
最新版主题标签云未采用本地js和css导致无法显示

### ISSUE THREAD

**Issue by barry200890** [qinhua/halo-theme-joe2.0#61]
**描述缺陷**
由于升级最新主题后，查看主页发现，3D标签云加载不出来了
请简洁而清晰的描述一下这个缺陷。
3D标签云加载不出来了
**如何复现**
在博客后台在线更新主题后可以看到
复现步骤如下:

1. 打开 "博客后台"
2. 点击 "joe主题在线更新"
3. 等待提示主题 "更新完成后"
4. 发生错误
![image](https://user-images.githubusercontent.com/65383345/147069899-70cd21a4-28be-4f3b-a43c-c097cb722628.png)

**期望结果**
应该使用本地js和css中的文件，加载出3d标签云，cdn不稳定会导致系统出现显示问题
简洁而清晰的描述一下你最终期望的结果。

**截图**
其他浏览器也一样：
![image](https://user-images.githubusercontent.com/65383345/147070318-38bfcbe7-af38-4f7f-bc04-f8db065598d0.png)

如有需要，可以附上一些截图。
其他问题：在后台添加的网易音乐的id，在前台播放的音乐不是同一个。（后台的id是从网易音乐官网找的，确定没问题，但是前台博客播放器里的音乐则不是这个歌曲。）

**PC 端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.11]
- 操作系统：[e.g. iOS]
- 浏览器：[e.g. chrome, safari]
- 版本：[e.g. 22]

**移动端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.11]
- 设备型号：[e.g. iPhone6]
- 操作系统：[e.g. iOS8.1]
- 浏览器：[e.g. stock browser, safari]
- 版本：[e.g. 22]

**额外信息**

可以添加一些额外的对我们处理这个问题有帮助的信息。

**Comment by qinhua** [comment]
1.0.8 不可能会引入 1.0.7 的资源，除非主题更新后有缓存。这个可以按文档中说的方式处理一下

**Comment by qinhua** [comment]
特别不建议使用在线更新，按文档中说的从主题包更新。

**Comment by barry200890** [comment]
哦，那就下载最新的主题包，手动更新么？

**Comment by barry200890** [comment]
建议还是将用到的js和css文件使用本地css和js文件，代替cdn中的，cdn中的资源加载缓慢会导致博客主页加载缓慢的问题，如图：
![image](https://user-images.githubusercontent.com/65383345/147307350-53412af6-f120-45de-ac05-a72aa6934a2c.png)

**Comment by barry200890** [comment]
还有在后台配置的网易音乐的id后，在前台展示的歌曲和实际网易云上的不是同一个歌曲。

**Comment by qinhua** [comment]
> 还有在后台配置的网易音乐的id后，在前台展示的歌曲和实际网易云上的不是同一个歌曲。

有些由于版权限制会被过滤，不然只有几秒

**Comment by qinhua** [comment]
> 建议还是将用到的js和css文件使用本地css和js文件，代替cdn中的，cdn中的资源加载缓慢会导致博客主页加载缓慢的问题，如图： ![image](https://user-images.githubusercontent.com/65383345/147307350-53412af6-f120-45de-ac05-a72aa6934a2c.png)

肯定不会优先用本地，本地才慢呢，只能说后面可以自定义 cdn 域名，用户可以把主题放到自己的cdn上去维护。

**Comment by barry200890** [comment]
哦，不知道为啥，我把主题设置里面那个使用cdn的开关关闭后，感觉起码本地加载那些js，css文件快了

**Comment by qinhua** [comment]
@barry200890 严格从 Release 中下载压缩包更新，然后按主题文档中的说明清除下主题缓存。
