### ISSUE TITLE
能否优化一下内容目录导航栏？

### ISSUE THREAD

**Issue by cosolar** [qinhua/halo-theme-joe2.0#62]
**你的建议是否涉及到一些现有的问题? 请描述清楚**

能否优化一下内容目录导航栏？
让导航预览大纲和内容部分分割开，别悬浮在内容上。

简单而清晰的问题描述。

![image](https://user-images.githubusercontent.com/28598727/147222236-a0bf3bec-321d-4333-b596-895f1f853d10.png)

![image](https://user-images.githubusercontent.com/28598727/147221730-51d2c974-88a7-4ceb-aa07-f6abb1558474.png)
https://www.androidperformance.com/2019/12/01/BlogMap/

**Comment by qinhua** [comment]
收到

**Comment by BaLaLaLs** [comment]
我也觉得这钟悬浮的设计不太好。。。

**Comment by qinhua** [comment]
@BaLaLaLs @cosolar V1.0.9 已做相关优化，请更新主题。
