### ISSUE TITLE
https页面表单搜索发出的是http请求被浏览器拦截

### ISSUE THREAD

**Issue by ocange** [qinhua/halo-theme-joe2.0#63]
**描述缺陷**

https域名下建站，https地址访问页面显示正常，但表单搜索或链接却是http的，导致浏览器提示表单不安全，提交浏览器仍提示"您即将提交的信息不安全"，提交后nginx虽说可以把http转到https，但浏览器提升有点影响使用体验~

**Comment by qinhua** [comment]
@ocange 具体是什么场景，有图吗，不太明白，只知道是混合内容的问题。

**Comment by ruibaby** [comment]
应该是博客设置中的博客地址是 http，改成 https 即可。

**Comment by ocange** [comment]
确实设置问题
