### ISSUE TITLE
文章页面中的[TOC] 目录，点击后跳转到新的页面了

### ISSUE THREAD

**Issue by Zinyan-Z** [qinhua/halo-theme-joe2.0#64]
**描述缺陷**

如果使用主题自带的侧边TOC目录浮动窗。点击时页面在当前页面中滑动到指定节点。
但是如果是markdown 文档自带TOC的标签显示的目录，点击的时候启动新的页面跳转到指定节点了。

**期望结果**

希望文章里面的TOC目录跳转不访问新的页面。

**截图**

![image](https://user-images.githubusercontent.com/6871017/147621144-54e8bd83-ebec-463f-9982-2e8e80c1925a.png)

**Comment by qinhua** [comment]
收到

**Comment by qinhua** [comment]
@Zinyan-Z 能提供一下这篇文章的链接我看一下吗

**Comment by Zinyan-Z** [comment]
@qinhua  https://zinyan.com/?p=183 这个地址的

**Comment by qinhua** [comment]
@Zinyan-Z 好的，收到，下个版本兼容一下内部目录

**Comment by qinhua** [comment]
@Zinyan-Z V1.0.9 已修复
