### ISSUE TITLE
点赞功能缺少key（Missing API access key）

### ISSUE THREAD

**Issue by boluofan** [qinhua/halo-theme-joe2.0#67]
**描述缺陷**
您好，我使用您做的这个halo主题，很好用。但有个问题：我用这个主题后。点赞文章和日志页的点赞功能异常，点赞后接口报错401（Missing API access key）。但是我已经开启api设置并配置相同的了api key 
**如何复现**

复现步骤如下:
随机测试我的一个博客文章点赞功能

1. 打开 "www.boluofan.top"
2. 点击 "任意一个文章"
3. 滚动到 "底部"，点击 "喜欢"按钮
4. 发生错误

**期望结果**
文章/日志 点赞功能正常

**截图**

![image](https://user-images.githubusercontent.com/40459801/148890944-02cdb14d-d68b-4610-9152-a585935241bd.png)

**PC 端 (请提供以下信息):**

- Halo 版本：1.4.2
- 操作系统：Win10
- 浏览器：chrome
- 版本：未知

**额外信息**

![image](https://user-images.githubusercontent.com/40459801/148891891-8d3bfc4f-9d7c-432b-8a59-6c69416c2abf.png)

- 我曾尝试自己修复，发现手动在post请求中添加"API-Authorization": apikey 请求头后该点赞接口请求成功，点赞生效。确定是缺少了apikey
- 我还浏览了您的个人博客，发现你博客使用的是和我同样的js，且未在js ajax中添加API-Authorization

**Comment by qinhua** [comment]
@boluofan 主题仅支持 Halo 1.4.11+ 版本

**Comment by qinhua** [comment]
下个版本，相关请求都会带上 `access_key`

**Comment by boluofan** [comment]
好的 收到 多谢

**Comment by boluofan** [comment]
你好，我想先自己修改下js引用。麻烦告诉我下文章页面的点赞和日志页面点赞的js是在哪个ftl里引用的？我需要移除自定义js☺

这两个

文章
https://cdn.jsdelivr.net/gh/qinhua/halo-theme-joe2.0@1.0.8/source/js/min/joe.post.min.js?v=1.0.8

日志
https://cdn.jsdelivr.net/gh/qinhua/halo-theme-joe2.0@1.0.8/source/js/min/joe.journals.min.js?v=1.0.8

**Comment by boluofan** [comment]
不用麻烦了 已经找到了 用GitHub搜索js 都在template/macro/tail.ftl下引用的😄

**Comment by qinhua** [comment]
@boluofan V1.0.9 已修复
