### ISSUE TITLE
缺少对于Objective-C代码语法高亮的支持

### ISSUE THREAD

**Issue by Peter-Huang0623** [qinhua/halo-theme-joe2.0#68]
目前使用的最新版本的主题，但是似乎缺少对于 OC 的语法支持，没有高亮，如果把语言改成 cpp，倒是可以有部分代码的高亮。

**Comment by qinhua** [comment]
@Peter-Huang0623 这个语言特性目前是没有引入的，后面可以按需要再加。

**Comment by qinhua** [comment]
@Peter-Huang0623 V1.0.9 已支持

> \```objectivec
这样就可以
\```
