### ISSUE TITLE
更新主题版本后 Katex 失效

### ISSUE THREAD

**Issue by Usocute** [qinhua/halo-theme-joe2.0#69]
**描述缺陷**

`1.0.6`版本主题更新到`1.0.7`、`1.0.8` 版本后 Katex 功能失效。

**期望结果**

Katex 功能正常

**截图**

- 后台
![后台](https://s4.ax1x.com/2022/01/12/7KsqaV.md.png)

- joe2.0
![前端页面](https://s4.ax1x.com/2022/01/12/7KyWe1.md.png)

- 更换主题后
![更换主题后](https://s4.ax1x.com/2022/01/12/7K6D0I.md.png)

**PC 端 (请提供以下信息):**

- Halo 版本：1.4.16
- 操作系统：windowns
- 浏览器：Edge
- 版本：97.0.1072.55

**移动端 (请提供以下信息):**

- Halo 版本：1.4.16
- 设备型号：Huawei Mate 40
- 操作系统：Android 11
- 浏览器：chrome
- 版本：96.0.4664.92

**额外信息**

- 已在后台开启Mathjax支持，并按照主题
- 已使用代码块来包裹要展示的公式，并指定语言类型为 `math`
- 切换主题后可正常渲染

**Comment by qinhua** [comment]
收到
