### ISSUE TITLE
PDF在文章中无法预览

### ISSUE THREAD

**Issue by windok88** [qinhua/halo-theme-joe2.0#72]
使用 joe-pdf 标签后无法预览PDF

> 文章的显示效果

![文章显示](https://user-images.githubusercontent.com/54491035/150337299-88b27e12-aa18-4ad9-ab21-041f2f862943.PNG)

> 文章的网页代码

![网页代码](https://user-images.githubusercontent.com/54491035/150336983-4cb7a4af-21b0-475e-8660-a8f56988e89a.PNG)

**Comment by qinhua** [comment]
收到，目前线上确实有这个问题，这个会在 `1.0.9` 修复。

**Comment by qinhua** [comment]
@windok88 V1.0.9 已修复，见 [Joe2.0 PDF 预览](https://bbchin.com/archives/style-guideline#pdf-%E9%A2%84%E8%A7%88)
