### ISSUE TITLE
文章页广告连接无法点击

### ISSUE THREAD

**Issue by AshinLin** [qinhua/halo-theme-joe2.0#73]
**描述缺陷**

文章叶广告，图片能正常显示，但是点击图片不会跳转广告链接，而是打开图片。
浏览器查看为img标签上多渲染了一个span标签。

**如何复现**

复现步骤如下:
加文章广告。

**期望结果**

正常跳转。

**额外信息**

ads_post.ftl文件，img少加了一个class，加上即可。

**Comment by qinhua** [comment]
@AshinLin 收到，已知问题，下版本一起修复，最近在面试

**Comment by qinhua** [comment]
@AshinLin V1.0.9 已修复
