### ISSUE TITLE
能否在随机图api加一个能设置发送Referer的选项？

### ISSUE THREAD

**Issue by Lilac-Dream** [qinhua/halo-theme-joe2.0#74]
自建api随机图库会根据Referer信息参考是否被盗链，但是主题设置的默认请求中是不带Referer信息的，所以能否设置随机图片api能够发送referer信息的选项？

**Comment by AshinLin** [comment]
> 自建api随机图库会根据Referer信息参考是否被盗链，但是主题设置的默认请求中是不带Referer信息的，所以能否设置随机图片api能够发送referer信息的选项？

好像是带的吧，我的正常

**Comment by qinhua** [comment]
@Lilac-Dream 我这边看到，目前请求是会自动带上 `referer` 的，看是不是配置了相应的 `CSP` 导致的。

**Comment by Lilac-Dream** [comment]
好像真的是CSP导致的。。。谢谢！F12发现api确实是带Referer信息的，打扰了QWQ
