### ISSUE TITLE
标签云更多选项位置出错

### ISSUE THREAD

**Issue by yumuing** [qinhua/halo-theme-joe2.0#77]
**描述缺陷**

标签云更多选择的位置飘到了标签云标题处，如下：
![image](https://user-images.githubusercontent.com/77838031/152685355-d799927f-7304-4145-ac1c-cfb0cf74aa70.png)

**如何复现**
打开http://[yumuing.top](http://yumuing.top/)
查看标签云位置

**Comment by qinhua** [comment]
@yumuing 从 Release 中下载 `1.0.8` 的包，`main` 分支上这里的样式可能忘提交了

**Comment by qinhua** [comment]
@yumuing 一定要从 Release 下载最新的包，新版本这里不会有这个问题了。
