### ISSUE TITLE
设置`ID型`的文章固定链接类型，在主页点开回复的评论之后，会显示服务器错误400

### ISSUE THREAD

**Issue by Lilac-Dream** [qinhua/halo-theme-joe2.0#79]
**描述缺陷**

设置**ID型**的文章固定链接类型，在**主页**点开**回复的评论**之后，会显示服务器错误400

**如何复现**
管理界面->系统->博客设置->高级选项->文章固定链接类型->ID型
![image](https://user-images.githubusercontent.com/49761134/152932993-ba3a99f7-f362-4bba-a863-3cf7af910a69.png)

然后回到博客首页点击回复的评论，出现错误400。
点开后网址类似：https://www.***.com/?p={id}/#6
![image](https://user-images.githubusercontent.com/49761134/152933006-c211f592-ce03-4fb9-b930-27aea8ea22ed.png)

**PC 端 (请提供以下信息):**

- Halo 版本：[1.4.17]
- 操作系统：[win11]
- 浏览器：[chrome]

**Comment by qinhua** [comment]
收到

**Comment by qinhua** [comment]
@Lilac-Dream V1.0.9 已修复

**Comment by Lilac-Dream** [comment]
(๑•̀ㅂ•́)و✧棒！
