### ISSUE TITLE
文章显示问题：已收录这里是写死的吗？

### ISSUE THREAD

**Issue by bxbdba** [qinhua/halo-theme-joe2.0#8]
大佬！
我这边新建一篇文章后，在点击预览的时候就看到文章页面是已收录的状态，这个我尚未发布，应该不可能是收录的吧。

**Comment by qinhua** [comment]
@bxbdba 默认会检查是否收录，没收录就自动去收录，目前是按地址收录。这个功能只是一个实验性的。不能作为真实参考，显示情况很复杂的。

我会在下个版本屏蔽预览模式下的收录检查。

**Comment by qinhua** [comment]
@bxbdba 1.0.2 版本已屏蔽预览模式下的收录检查。

**Comment by bxbdba** [comment]
大佬辛苦了！
