### ISSUE TITLE
文章详情页侧边栏 开启后，文章页的“广告”图片，超链接丢失了

### ISSUE THREAD

**Issue by Little-Qiu** [qinhua/halo-theme-joe2.0#80]

**Comment by qinhua** [comment]
@Little-Qiu 是指文章页底部的广告图片点不了吗？

**Comment by Little-Qiu** [comment]
@qinhua 是的，配置广告后，文章 底部的广告点击跳转不了，点击广告图片，直接图片放大了。上面我的描述也不准确，我这边不管配不配置侧边栏开启或者关闭，广告都是同样点击跳转不了。

**Comment by faonecze** [comment]
恩,文章底部添加广告后,点击广告不会跳转到广告链接,而是放大图片.

**Comment by qinhua** [comment]
@faonecze V1.0.9 已修复
