### ISSUE TITLE
文章内设置了内部跳转的a标签，无法设置页面内跳转，会打开一个新页面，a 标签的target 会被覆盖重写

### ISSUE THREAD

**Issue by Little-Qiu** [qinhua/halo-theme-joe2.0#81]
![image](https://user-images.githubusercontent.com/20431482/153699596-31c719e6-b5d8-40b0-bed9-ec66fc05d732.png)

**Comment by qinhua** [comment]
@Little-Qiu 已知问题，后续会修复

**Comment by qinhua** [comment]
@Little-Qiu 目前页面内所有链接都做了新页面打开的处理

**Comment by qinhua** [comment]
@Little-Qiu V1.0.9 对文章内部锚点保持了浏览器默认的行为，可以跳转了，外部链接保持不变。
