### ISSUE TITLE
日志，开启评论回复邮箱有通知后台和前台无法展现

### ISSUE THREAD

**Issue by faonecze** [qinhua/halo-theme-joe2.0#84]
**描述缺陷**

测试评论日志页面某个时间段消息，回复提交时web页面提醒内容手机无法查看，而且回复消息只有邮箱能看到，后台无法看到评论也无法审核，

**如何复现**

复现步骤如下:

1. 打开 "日志页面"
2. 点击 "评论图标"
3. 填写内容 "提交评论"
4. 发生错误

**期望结果**

希望后台可以正常查阅审核评论

**截图**

如有需要，可以附上一些截图。

**移动端 (请提供以下信息):**

- Halo 版本：[e.g. 1.4.17]
- 操作系统：[e.g. 鸿蒙]
- 浏览器：[e.g. 谷歌]
- 版本：[e.g. 98.0]

**额外信息**
无

**Comment by qinhua** [comment]
@faonecze 具体提示什么错误呢？

**Comment by faonecze** [comment]
![](https://img.cnelite.org/upload/2202/accf017210ef9cce.png)
提示啥也看不见.
电脑手机情况一样,可评论后台前台都看不到,只有邮箱可以.  [页面地址](https://auok.run/journals)

**Comment by faonecze** [comment]
好吧,我好像找到位置了,原来是没找对地址

![](https://img.cnelite.org/upload/2202/a9224d63cf69ffe5.png)
