### ISSUE TITLE
网易云音乐配置无效吗？

### ISSUE THREAD

**Issue by rookiehander** [qinhua/halo-theme-joe2.0#87]
![image](https://user-images.githubusercontent.com/61374918/156524961-2d8b6b07-1407-4dbf-a783-e01e9bc00468.png)

**Comment by qinhua** [comment]
试试这个 6827562995

**Comment by rookiehander** [comment]
哦哦 ，是歌单id嘛？我连接的歌单的链接。我的我的

**Comment by qinhua** [comment]
> Refere

嗯，网址中的那串数字就是，填写到主题设置里就可以。
