### ISSUE TITLE
左侧的点赞评论分享按钮显示异常

### ISSUE THREAD

**Issue by 52lemon6** [qinhua/halo-theme-joe2.0#89]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.4.17

### 平台

桌面端

### 操作系统

Windows11

### 浏览器

chrome版本 98.0.4758.102（正式版本） （64 位）

### 描述缺陷

新版问斩左侧按钮自适应有问题，非全屏或有缩放操作会导致显示不全
![image](https://user-images.githubusercontent.com/40059643/156794730-b0ec2b0d-5fb7-44a6-8734-48521c2e9fce.png)

### 期望结果

希望侧边必须有多少宽度才会显示

**Comment by qinhua** [comment]
@52lemon6 这个暂时没做适配，后面再优化

**Comment by qinhua** [comment]
@52lemon6 新版本已做优化，请升级以解决，感谢支持。
