### ISSUE TITLE
友链中的logo建议

### ISSUE THREAD

**Issue by IILee5** [qinhua/halo-theme-joe2.0#9]
我看见友情链接中，logo地址是直接获取的halo后台实际地址。
![image](https://user-images.githubusercontent.com/40862062/141601125-61aaff6e-3dd8-4fe9-bfe4-7e9e7031ebe2.png)
建议更新为博客地址后面拼接`/avatar`或`/logo`，例如：`https://www.demo.cn/avatar`，这样便可实时更新logo地址，而不至于每次logo更新都去通知友站更新logo。

**Comment by qinhua** [comment]
有道理，为了规范和美观，后面会换成 `<#assign logo_url = blog_url + '/logo'>` 。
- 博客地址/logo
- 博客地址/avatar

不过要提醒一下，简写地址本质是重定向，所以后台管理中不要也设置为简写地址，不然可能出现重定向死循环。

下版本见哈。

**Comment by IILee5** [comment]
哈哈，我大概也猜到了大佬后台使用的是简写地址～所以我自己这个版本把这个地址写死了

**Comment by qinhua** [comment]
> 哈哈，我大概也猜到了大佬后台使用的是简写地址～所以我自己这个版本把这个地址写死了
太过优秀，这都能猜到 😆

**Comment by IILee5** [comment]
因为我自己配置的时候发现地址变成实际地址了，而在博主的网站上看到的却是简写的地址😄️

**Comment by qinhua** [comment]
@IILee5 1.0.3 中已做相应变更。
