### ISSUE TITLE
希望鼠标皮肤的url可以带原域名

### ISSUE THREAD

**Issue by 52lemon6** [qinhua/halo-theme-joe2.0#90]
### 你当前使用的版本

1.0.9

### 你的建议是否涉及到一些现有的问题？

如使用自定义cdn功能时，cdn（cdn.xx.cn)设置了防盗链，只允许xx.cn访问此时（此时效果为通过xx.cn访问cdn.xx.cn状态为200，直接访问cdn.xx.cn状态为403）鼠标皮肤的url请求是不带原站referer的其他的js和css是带原站referer请求的

### 描述你想实现的效果

希望鼠标皮肤url请求可以带上原站referer参数

### 附加信息

![image](https://user-images.githubusercontent.com/40059643/156922248-4e3ed8cb-1e48-48b1-a6d4-129cfa6023eb.png)
![image](https://user-images.githubusercontent.com/40059643/156922050-43ca4a9b-ca0e-4cb4-8e22-429187b7c78b.png)
以上为带原站referer参数请求
![image](https://user-images.githubusercontent.com/40059643/156922077-4900330c-be0d-4dab-9f4e-560abbd1ab3a.png)
![image](https://user-images.githubusercontent.com/40059643/156922199-86a5b44f-ddc5-414d-9c6d-9c3ce0c16178.png)
以上为不带原站referer参数请求

**Comment by qinhua** [comment]
referer 默认会自己带的，你的意思应该是想前端去修改这个 referer，这里恐怕不太好实现，建议从 CDN 策略那里调整会更容易些

**Comment by qinhua** [comment]
@52lemon6 你在 CDN 的防盗链白名单里把你的 CDN 域名 `cdn.xx.cn` 也加一下就好了。

**Comment by 52lemon6** [comment]
> 

嗯嗯~~好哒~~

**Comment by 52lemon6** [comment]
> @52lemon6你在CDN的防盗链白里把你的CDN域名`cdn.xx.cn`也加一下就好了。

嗯嗯~好哒~
