### ISSUE TITLE
更新主题报错

### ISSUE THREAD

**Issue by Soulballad** [qinhua/halo-theme-joe2.0#91]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.4.17

### 平台

桌面端

### 操作系统

Windows10

### 浏览器

Edge

### 描述缺陷

离线更新主题，出现网络错误
![image](https://user-images.githubusercontent.com/19262272/157053343-2b26280a-b4f6-472b-b8ed-129ffc5491a2.png)

### 如何复现

更多->从主题包更新->上传主题包，然后更新，失败

**Comment by Soulballad** [comment]
![image](https://user-images.githubusercontent.com/19262272/157055228-85afb500-5c11-4fb9-8ead-a832cf713d8b.png)

**Comment by qinhua** [comment]
主题包解压后直接传到服务器 `~/.halo/templates/themes/joe2.0` 中覆盖即可，安装其它主题同理，简单干脆。

**Comment by Soulballad** [comment]
好的
