### ISSUE TITLE
新版手机浏览适配是有问题么

### ISSUE THREAD

**Issue by little-2pig** [qinhua/halo-theme-joe2.0#92]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.4.17

### 平台

移动端

### 操作系统

ios，Android

### 浏览器

Google

### 描述缺陷

不适配，UI样式不显示，不知道是不是加了自己cdn问题，网页端没问题

**Comment by qinhua** [comment]
请提供再多一些信息，以便我们帮助排查，比如出现该问题的链接地址。

**Comment by little-2pig** [comment]
https://www.little2pig.work/，师傅可用手机帮忙看看，我pc端访问正常

**Comment by qinhua** [comment]
@little-2pig 我这边手机可以打开，记得清一下手机浏览器缓存再试试。
