### ISSUE TITLE
文章附件下载和管理功能

### ISSUE THREAD

**Issue by XiaoMoDonnie** [qinhua/halo-theme-joe2.0#93]
### 你当前使用的版本

v1.0.9

### 你的建议是否涉及到一些现有的问题？

我想给文章添加一些可以提供给用户下载的附件，但是没有很好的办法进行管理，虽然在markdown中支持有网盘形式的样式，但是还是希望能够对附件有一个更详细的描述面板

### 描述你想实现的效果

文章详情页中是不是可以做那种文件（文章附件）下载的面板，包括密码验证才可以下载这种，比如
![image](https://user-images.githubusercontent.com/49033970/158006660-ca096a16-1d96-4403-a7bc-71a84ed171f6.png)

**Comment by qinhua** [comment]
主题目前不支持这个，不过可以自己实现，搭建相关服务即可。

**Comment by XiaoMoDonnie** [comment]
好的，谢谢大佬，不过也还是想问一下后续有打算做这个吗

**Comment by qinhua** [comment]
@XiaoMoDonnie 这个需要 halo-admin 这个项目提供支持。

**Comment by XiaoMoDonnie** [comment]
好滴，我去问问作者，对了，不知道为啥，我现在用的这个版本，移动端回到顶部的按钮（文章详细页面的小火箭）失效了，博客地址：https://b.925i.cn

**Comment by qinhua** [comment]
> 好滴，我去问问作者，对了，不知道为啥，我现在用的这个版本，移动端回到顶部的按钮（文章详细页面的小火箭）失效了（补充：环境是QQ内置浏览器中），博客地址：https://b.925i.cn

我这边QQ内置浏览器可以返回顶部，是什么手机型号和qq版本

**Comment by XiaoMoDonnie** [comment]
QQ8.8.80.7400   Redmi k30至尊纪念版  MIUI12.5.70  很奇怪

**Comment by qinhua** [comment]
@XiaoMoDonnie 这个需求应该提给 `halo` 和 `halo-admin` 这两个项目，主题只是展示。
