### ISSUE TITLE
你好主题设置-其他-没有开启cdn类型，但是仍然存在加载cdn.jsdelivr.net

### ISSUE THREAD

**Issue by nanjunyu** [qinhua/halo-theme-joe2.0#94]
### 你当前使用的版本

1.0.9

### 你的建议是否涉及到一些现有的问题？

你好主题设置-其他-没有开启cdn类型，但是仍然存在加载cdn.jsdelivr.net，好像是一张图片，而且很慢每次需要十几秒

### 描述你想实现的效果

希望不加载，或者可以调整源的地址或者有别的方案，谢谢

### 附加信息

慢sql地址:https://cdn.jsdelivr.net/gh/fghrsh/live2d_api@1.0.1/model/Potion-Maker/Pio/textures/animal-costume-racoon.png

好像是看板娘的资源。。

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/23097168/158044069-94a27545-2497-48b8-9519-b028d2be2976.png">

![image](https://user-images.githubusercontent.com/23097168/158044073-4eeab436-502e-4504-b08b-324dec597b70.png)

**Comment by qinhua** [comment]
目前有些资源内部还有循环引用的资源，下个版本再做一轮清理

**Comment by qinhua** [comment]
@nanjunyu 新版本已全量移除，请升级以解决，感谢支持。
