### ISSUE TITLE
微信浏览器“返回顶部”失效？

### ISSUE THREAD

**Issue by faonecze** [qinhua/halo-theme-joe2.0#96]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.4.17

### 平台

移动端

### 操作系统

鸿蒙

### 浏览器

微信

### 在线站点地址

auok.run

### 描述缺陷

微信点击返回顶部失效，无法正常使用。

### 如何复现

目前访问站点即可。

### 附加信息

有望修复，感谢

**Comment by qinhua** [comment]
@faonecze 近期会尝试复现并修复

**Comment by qinhua** [comment]
@faonecze 新版本已修复，请升级以解决，感谢支持。
