### ISSUE TITLE
新建任意页面访问正常但弹窗报 404

### ISSUE THREAD

**Issue by Qxin-X** [qinhua/halo-theme-joe2.0#97]
### 是什么版本出现了此问题？

1.0.9

### Halo 版本

1.4.17

### 平台

桌面端

### 操作系统

win10

### 浏览器

谷歌，edge

### 在线站点地址

https://blog.xieqingxin.com/test

### 描述缺陷

新建任意页面访问正常但弹窗报 404，检查后发现这个请求路径 404，halo后台日志无相关报错，服务器网站日志相关报错。

在 halo 提的 issues ：[新建任意页面访问正常但弹窗报 404](https://github.com/halo-dev/halo/issues/1755) 

### 附加信息

![屏幕截图 2022-03-17 145319](https://user-images.githubusercontent.com/66522154/158758893-c175cea3-f339-448b-bd25-c9aaa54e3ea3.png)
![屏幕截图 2022-03-17 151815](https://user-images.githubusercontent.com/66522154/158758930-bf9e555e-4aa9-40f0-8076-37f0a6343eea.png)
![屏幕截图 2022-03-17 152012](https://user-images.githubusercontent.com/66522154/158758830-2fa592ad-abfd-4330-a246-074600d9df2a.png)

**Comment by qinhua** [comment]
@Qxin-X 嗯，已确认是 **路径中的页面id格式问题** 导致的 404。下版本修复

**Comment by qinhua** [comment]
@Qxin-X 新版本已修复，请升级以解决，感谢支持。
