### ISSUE TITLE
文章中划线无法正常显示

### ISSUE THREAD

**Issue by ayuanaa** [qinhua/halo-theme-joe2.0#98]
### 是什么版本出现了此问题？

2.0

### Halo 版本

2.0

### 平台

桌面端

### 在线站点地址

https://www.ututut.top/

### 描述缺陷

在文章处为链接加入中划线后即时预览可以看到生效，但是到了预览中却无法生效，默认主题正常显示

### 附加信息

https://www.ututut.top/upload/2022/03/Snipaste_2022-03-20_00-43-38-698a10aa486247bfb98a375510a151d5.png

**Comment by qinhua** [comment]
@ayuanaa 这种加了删除线的链接应该不能再点击了吧，如果是的话，下个版本我可以优化一下

**Comment by ayuanaa** [comment]
还是可以点击的

**Comment by qinhua** [comment]
@ayuanaa 新版本已修复，请升级以解决，感谢支持。
