### ISSUE TITLE
顶部菜单栏页面和选中动画无法对应

### ISSUE THREAD

**Issue by hapke24** [qinhua/halo-theme-joe2.0#99]
### 是什么版本出现了此问题？

2.0

### Halo 版本

1.4.17

### 平台

桌面端

### 操作系统

Windows11

### 浏览器

Edge

### 描述缺陷

当菜单栏排序“首页”不在最前时，会出现“首页”和前面的菜单选项显示混乱的问题。
- 菜单排序
![image](https://user-images.githubusercontent.com/49407099/159230408-958f5cf2-d01b-4ee6-956b-da85f1cf7497.png)
- 现在为主页，菜单栏显示的却是文章归档
![image](https://user-images.githubusercontent.com/49407099/159230375-01e30f57-61e0-43b9-9abc-7d3e7e14385d.png)
- 主页后面的菜单选项显示正常

### 如何复现

将菜单排序改为改为第一个不是主页可以完美复现
![image](https://user-images.githubusercontent.com/49407099/159230408-958f5cf2-d01b-4ee6-956b-da85f1cf7497.png)

### 期望结果

希望“主页”即使不在最前也可以显示正确。

**Comment by qinhua** [comment]
@hapke24 收到，下版本修复它

**Comment by qinhua** [comment]
@hapke24 新版本已修复，请升级以解决，感谢支持。

**Comment by qinhua** [comment]
@hapke24 新版本已修复，请升级以解决，感谢支持。

**Comment by qinhua** [comment]
@hapke24 新版本已修复，请升级以解决，感谢支持。

**Comment by qinhua** [comment]
@hapke24 新版本已修复，请升级以解决，感谢支持。
